# unimind/models/native/vocabulary_extended.py
# Extended English Vocabulary - Additional thousands of words

"""
Extended Vocabulary for Enhanced NLU

This module extends the core vocabulary with thousands of additional words
covering:
- Common verbs (500+)
- Common nouns (1000+)
- Common adjectives (500+)
- Common adverbs (200+)
- Domain-specific vocabulary
"""

from typing import Dict, List, Set
from .vocabulary import (
    WordEntry, PartOfSpeech, WordFrequency, EnglishVocabulary, get_vocabulary
)


# =============================================================================
# EXTENDED VERBS (500+ common verbs)
# =============================================================================

EXTENDED_VERBS = {
    # Communication verbs
    "speak": WordEntry("speak", [PartOfSpeech.VERB], ["To talk, to express verbally"], WordFrequency.CORE_500, 
                       synonyms=["talk", "say", "tell"]),
    "listen": WordEntry("listen", [PartOfSpeech.VERB], ["To hear attentively"], WordFrequency.CORE_500,
                        synonyms=["hear", "attend"]),
    "read": WordEntry("read", [PartOfSpeech.VERB], ["To interpret written text"], WordFrequency.CORE_500),
    "write": WordEntry("write", [PartOfSpeech.VERB], ["To form letters/words"], WordFrequency.CORE_500,
                       synonyms=["compose", "pen"]),
    "explain": WordEntry("explain", [PartOfSpeech.VERB], ["To make clear"], WordFrequency.CORE_500,
                         synonyms=["clarify", "describe"]),
    "describe": WordEntry("describe", [PartOfSpeech.VERB], ["To give account of"], WordFrequency.CORE_500,
                          synonyms=["depict", "portray"]),
    "discuss": WordEntry("discuss", [PartOfSpeech.VERB], ["To talk about"], WordFrequency.CORE_500,
                         synonyms=["debate", "converse"]),
    "argue": WordEntry("argue", [PartOfSpeech.VERB], ["To present reasons"], WordFrequency.CORE_500,
                       synonyms=["debate", "dispute"]),
    "suggest": WordEntry("suggest", [PartOfSpeech.VERB], ["To propose"], WordFrequency.CORE_500,
                         synonyms=["propose", "recommend"]),
    "recommend": WordEntry("recommend", [PartOfSpeech.VERB], ["To advise, endorse"], WordFrequency.CORE_500,
                           synonyms=["suggest", "advise"]),
    "announce": WordEntry("announce", [PartOfSpeech.VERB], ["To make known publicly"], WordFrequency.CORE_1000,
                          synonyms=["declare", "proclaim"]),
    "claim": WordEntry("claim", [PartOfSpeech.VERB], ["To assert, to demand"], WordFrequency.CORE_1000,
                       synonyms=["assert", "state"]),
    "deny": WordEntry("deny", [PartOfSpeech.VERB], ["To refuse, to reject"], WordFrequency.CORE_1000,
                      synonyms=["refuse", "reject"], antonyms=["admit", "confirm"]),
    "admit": WordEntry("admit", [PartOfSpeech.VERB], ["To acknowledge, to allow entry"], WordFrequency.CORE_1000,
                       synonyms=["acknowledge", "confess"]),
    "confirm": WordEntry("confirm", [PartOfSpeech.VERB], ["To verify, to validate"], WordFrequency.CORE_1000,
                         synonyms=["verify", "validate"]),
    "promise": WordEntry("promise", [PartOfSpeech.VERB], ["To pledge, to assure"], WordFrequency.CORE_1000,
                         synonyms=["pledge", "vow"]),
    "warn": WordEntry("warn", [PartOfSpeech.VERB], ["To caution, to alert"], WordFrequency.CORE_1000,
                      synonyms=["caution", "alert"]),
    "apologize": WordEntry("apologize", [PartOfSpeech.VERB], ["To express regret"], WordFrequency.COMMON,
                           synonyms=["express regret"]),
    "thank": WordEntry("thank", [PartOfSpeech.VERB], ["To express gratitude"], WordFrequency.CORE_500),
    "greet": WordEntry("greet", [PartOfSpeech.VERB], ["To welcome"], WordFrequency.COMMON,
                       synonyms=["welcome", "salute"]),
    
    # Mental verbs
    "believe": WordEntry("believe", [PartOfSpeech.VERB], ["To accept as true"], WordFrequency.CORE_500,
                         synonyms=["trust", "accept"]),
    "understand": WordEntry("understand", [PartOfSpeech.VERB], ["To comprehend"], WordFrequency.CORE_500,
                            synonyms=["comprehend", "grasp"]),
    "learn": WordEntry("learn", [PartOfSpeech.VERB], ["To acquire knowledge"], WordFrequency.CORE_500,
                       synonyms=["study", "master"]),
    "remember": WordEntry("remember", [PartOfSpeech.VERB], ["To recall from memory"], WordFrequency.CORE_500,
                          synonyms=["recall", "recollect"], antonyms=["forget"]),
    "forget": WordEntry("forget", [PartOfSpeech.VERB], ["To fail to remember"], WordFrequency.CORE_500,
                        antonyms=["remember"]),
    "imagine": WordEntry("imagine", [PartOfSpeech.VERB], ["To form mental image"], WordFrequency.CORE_500,
                         synonyms=["visualize", "envision"]),
    "wonder": WordEntry("wonder", [PartOfSpeech.VERB], ["To be curious about"], WordFrequency.CORE_500,
                        synonyms=["ponder", "question"]),
    "realize": WordEntry("realize", [PartOfSpeech.VERB], ["To become aware of"], WordFrequency.CORE_500,
                         synonyms=["recognize", "understand"]),
    "recognize": WordEntry("recognize", [PartOfSpeech.VERB], ["To identify, to acknowledge"], WordFrequency.CORE_500,
                           synonyms=["identify", "acknowledge"]),
    "consider": WordEntry("consider", [PartOfSpeech.VERB], ["To think about carefully"], WordFrequency.CORE_500,
                          synonyms=["contemplate", "ponder"]),
    "decide": WordEntry("decide", [PartOfSpeech.VERB], ["To make a choice"], WordFrequency.CORE_500,
                        synonyms=["choose", "determine"]),
    "expect": WordEntry("expect", [PartOfSpeech.VERB], ["To anticipate"], WordFrequency.CORE_500,
                        synonyms=["anticipate", "await"]),
    "hope": WordEntry("hope", [PartOfSpeech.VERB], ["To desire with expectation"], WordFrequency.CORE_500,
                      synonyms=["wish", "desire"]),
    "wish": WordEntry("wish", [PartOfSpeech.VERB], ["To desire, to want"], WordFrequency.CORE_500,
                      synonyms=["desire", "hope"]),
    "prefer": WordEntry("prefer", [PartOfSpeech.VERB], ["To like better"], WordFrequency.CORE_1000,
                        synonyms=["favor", "choose"]),
    "doubt": WordEntry("doubt", [PartOfSpeech.VERB], ["To question, to be uncertain"], WordFrequency.CORE_1000,
                       synonyms=["question", "distrust"]),
    "suspect": WordEntry("suspect", [PartOfSpeech.VERB], ["To believe to be guilty"], WordFrequency.CORE_1000,
                         synonyms=["mistrust"]),
    "assume": WordEntry("assume", [PartOfSpeech.VERB], ["To take for granted"], WordFrequency.CORE_1000,
                        synonyms=["presume", "suppose"]),
    "suppose": WordEntry("suppose", [PartOfSpeech.VERB], ["To assume, to believe"], WordFrequency.CORE_1000,
                         synonyms=["assume", "presume"]),
    "guess": WordEntry("guess", [PartOfSpeech.VERB], ["To estimate without facts"], WordFrequency.CORE_1000,
                       synonyms=["estimate", "suppose"]),
    "predict": WordEntry("predict", [PartOfSpeech.VERB], ["To forecast"], WordFrequency.CORE_1000,
                         synonyms=["forecast", "foretell"]),
    "plan": WordEntry("plan", [PartOfSpeech.VERB, PartOfSpeech.NOUN], ["To arrange, to design"], WordFrequency.CORE_500,
                      synonyms=["arrange", "organize"]),
    "prepare": WordEntry("prepare", [PartOfSpeech.VERB], ["To make ready"], WordFrequency.CORE_500,
                         synonyms=["ready", "arrange"]),
    "focus": WordEntry("focus", [PartOfSpeech.VERB], ["To concentrate"], WordFrequency.CORE_1000,
                       synonyms=["concentrate", "center"]),
    "analyze": WordEntry("analyze", [PartOfSpeech.VERB], ["To examine in detail"], WordFrequency.COMMON,
                         synonyms=["examine", "study"]),
    "evaluate": WordEntry("evaluate", [PartOfSpeech.VERB], ["To assess, to judge"], WordFrequency.COMMON,
                          synonyms=["assess", "judge"]),
    "compare": WordEntry("compare", [PartOfSpeech.VERB], ["To examine similarities"], WordFrequency.CORE_1000,
                         synonyms=["contrast", "relate"]),
    
    # Physical action verbs
    "open": WordEntry("open", [PartOfSpeech.VERB], ["To make accessible"], WordFrequency.CORE_500,
                      antonyms=["close"]),
    "close": WordEntry("close", [PartOfSpeech.VERB], ["To shut, to end"], WordFrequency.CORE_500,
                       synonyms=["shut"], antonyms=["open"]),
    "start": WordEntry("start", [PartOfSpeech.VERB], ["To begin"], WordFrequency.CORE_500,
                       synonyms=["begin", "commence"], antonyms=["stop", "end"]),
    "stop": WordEntry("stop", [PartOfSpeech.VERB], ["To cease, to halt"], WordFrequency.CORE_500,
                      synonyms=["halt", "cease"], antonyms=["start", "continue"]),
    "continue": WordEntry("continue", [PartOfSpeech.VERB], ["To proceed, to persist"], WordFrequency.CORE_500,
                          synonyms=["proceed", "persist"], antonyms=["stop"]),
    "finish": WordEntry("finish", [PartOfSpeech.VERB], ["To complete"], WordFrequency.CORE_500,
                        synonyms=["complete", "end"], antonyms=["start", "begin"]),
    "begin": WordEntry("begin", [PartOfSpeech.VERB], ["To start"], WordFrequency.CORE_500,
                       synonyms=["start", "commence"], antonyms=["end", "finish"]),
    "end": WordEntry("end", [PartOfSpeech.VERB, PartOfSpeech.NOUN], ["To finish, to conclude"], WordFrequency.CORE_500,
                     synonyms=["finish", "conclude"], antonyms=["begin", "start"]),
    "hold": WordEntry("hold", [PartOfSpeech.VERB], ["To grasp, to contain"], WordFrequency.CORE_500,
                      synonyms=["grasp", "grip"]),
    "carry": WordEntry("carry", [PartOfSpeech.VERB], ["To transport"], WordFrequency.CORE_500,
                       synonyms=["transport", "convey"]),
    "bring": WordEntry("bring", [PartOfSpeech.VERB], ["To carry toward"], WordFrequency.CORE_500,
                       synonyms=["deliver", "convey"]),
    "put": WordEntry("put", [PartOfSpeech.VERB], ["To place"], WordFrequency.CORE_500,
                     synonyms=["place", "set"]),
    "set": WordEntry("set", [PartOfSpeech.VERB], ["To place, to establish"], WordFrequency.CORE_500,
                     synonyms=["place", "put"]),
    "turn": WordEntry("turn", [PartOfSpeech.VERB], ["To rotate, to change direction"], WordFrequency.CORE_500,
                      synonyms=["rotate", "spin"]),
    "move": WordEntry("move", [PartOfSpeech.VERB], ["To change position"], WordFrequency.CORE_500,
                      synonyms=["shift", "relocate"]),
    "run": WordEntry("run", [PartOfSpeech.VERB], ["To move quickly"], WordFrequency.CORE_500,
                     synonyms=["sprint", "dash"], antonyms=["walk"]),
    "walk": WordEntry("walk", [PartOfSpeech.VERB], ["To move on foot"], WordFrequency.CORE_500,
                      antonyms=["run"]),
    "sit": WordEntry("sit", [PartOfSpeech.VERB], ["To be seated"], WordFrequency.CORE_500,
                     antonyms=["stand"]),
    "stand": WordEntry("stand", [PartOfSpeech.VERB], ["To be upright"], WordFrequency.CORE_500,
                       antonyms=["sit"]),
    "wait": WordEntry("wait", [PartOfSpeech.VERB], ["To remain, to stay"], WordFrequency.CORE_500,
                      synonyms=["remain", "stay"]),
    "stay": WordEntry("stay", [PartOfSpeech.VERB], ["To remain"], WordFrequency.CORE_500,
                      synonyms=["remain", "wait"], antonyms=["leave"]),
    "play": WordEntry("play", [PartOfSpeech.VERB], ["To engage in activity"], WordFrequency.CORE_500,
                      antonyms=["work"]),
    "watch": WordEntry("watch", [PartOfSpeech.VERB], ["To observe"], WordFrequency.CORE_500,
                       synonyms=["observe", "view"]),
    "read": WordEntry("read", [PartOfSpeech.VERB], ["To interpret text"], WordFrequency.CORE_500),
    "write": WordEntry("write", [PartOfSpeech.VERB], ["To inscribe"], WordFrequency.CORE_500,
                       synonyms=["inscribe", "compose"]),
    "eat": WordEntry("eat", [PartOfSpeech.VERB], ["To consume food"], WordFrequency.CORE_500,
                     synonyms=["consume", "dine"]),
    "drink": WordEntry("drink", [PartOfSpeech.VERB], ["To consume liquid"], WordFrequency.CORE_500,
                       synonyms=["sip", "consume"]),
    "sleep": WordEntry("sleep", [PartOfSpeech.VERB], ["To rest unconsciously"], WordFrequency.CORE_500,
                       synonyms=["rest", "slumber"], antonyms=["wake"]),
    "wake": WordEntry("wake", [PartOfSpeech.VERB], ["To stop sleeping"], WordFrequency.CORE_500,
                      synonyms=["awaken"], antonyms=["sleep"]),
    "send": WordEntry("send", [PartOfSpeech.VERB], ["To dispatch"], WordFrequency.CORE_500,
                      synonyms=["dispatch", "transmit"], antonyms=["receive"]),
    "receive": WordEntry("receive", [PartOfSpeech.VERB], ["To get, to obtain"], WordFrequency.CORE_500,
                         synonyms=["get", "obtain"], antonyms=["send"]),
    "buy": WordEntry("buy", [PartOfSpeech.VERB], ["To purchase"], WordFrequency.CORE_500,
                     synonyms=["purchase", "acquire"], antonyms=["sell"]),
    "sell": WordEntry("sell", [PartOfSpeech.VERB], ["To exchange for money"], WordFrequency.CORE_500,
                      antonyms=["buy"]),
    "pay": WordEntry("pay", [PartOfSpeech.VERB], ["To give money for"], WordFrequency.CORE_500,
                     synonyms=["compensate"]),
    "spend": WordEntry("spend", [PartOfSpeech.VERB], ["To use money/time"], WordFrequency.CORE_500,
                       antonyms=["save"]),
    "save": WordEntry("save", [PartOfSpeech.VERB], ["To rescue, to keep"], WordFrequency.CORE_500,
                      synonyms=["rescue", "preserve"], antonyms=["spend"]),
    "lose": WordEntry("lose", [PartOfSpeech.VERB], ["To misplace, to fail"], WordFrequency.CORE_500,
                      antonyms=["find", "win"]),
    "win": WordEntry("win", [PartOfSpeech.VERB], ["To succeed, to triumph"], WordFrequency.CORE_500,
                     synonyms=["triumph", "succeed"], antonyms=["lose"]),
    "change": WordEntry("change", [PartOfSpeech.VERB], ["To alter, to modify"], WordFrequency.CORE_500,
                        synonyms=["alter", "modify"]),
    "follow": WordEntry("follow", [PartOfSpeech.VERB], ["To come after"], WordFrequency.CORE_500,
                        synonyms=["trail", "pursue"], antonyms=["lead"]),
    "lead": WordEntry("lead", [PartOfSpeech.VERB], ["To guide, to direct"], WordFrequency.CORE_500,
                      synonyms=["guide", "direct"], antonyms=["follow"]),
    "meet": WordEntry("meet", [PartOfSpeech.VERB], ["To come together"], WordFrequency.CORE_500,
                      synonyms=["encounter", "gather"]),
    "show": WordEntry("show", [PartOfSpeech.VERB], ["To display, to demonstrate"], WordFrequency.CORE_500,
                      synonyms=["display", "demonstrate"], antonyms=["hide"]),
    "hide": WordEntry("hide", [PartOfSpeech.VERB], ["To conceal"], WordFrequency.CORE_500,
                      synonyms=["conceal", "cover"], antonyms=["show", "reveal"]),
    "build": WordEntry("build", [PartOfSpeech.VERB], ["To construct"], WordFrequency.CORE_500,
                       synonyms=["construct", "create"], antonyms=["destroy"]),
    "create": WordEntry("create", [PartOfSpeech.VERB], ["To make, to produce"], WordFrequency.CORE_500,
                        synonyms=["make", "produce"], antonyms=["destroy"]),
    "destroy": WordEntry("destroy", [PartOfSpeech.VERB], ["To demolish"], WordFrequency.CORE_1000,
                         synonyms=["demolish", "ruin"], antonyms=["create", "build"]),
    "help": WordEntry("help", [PartOfSpeech.VERB], ["To assist"], WordFrequency.CORE_500,
                      synonyms=["assist", "aid"]),
    "support": WordEntry("support", [PartOfSpeech.VERB, PartOfSpeech.NOUN], ["To assist, to hold up"], WordFrequency.CORE_500,
                         synonyms=["assist", "aid"]),
    "develop": WordEntry("develop", [PartOfSpeech.VERB], ["To grow, to create"], WordFrequency.CORE_500,
                         synonyms=["grow", "evolve"]),
    "improve": WordEntry("improve", [PartOfSpeech.VERB], ["To make better"], WordFrequency.CORE_500,
                         synonyms=["enhance", "better"], antonyms=["worsen"]),
    "increase": WordEntry("increase", [PartOfSpeech.VERB], ["To grow larger"], WordFrequency.CORE_500,
                          synonyms=["grow", "rise"], antonyms=["decrease"]),
    "reduce": WordEntry("reduce", [PartOfSpeech.VERB], ["To make smaller"], WordFrequency.CORE_500,
                        synonyms=["decrease", "lessen"], antonyms=["increase"]),
    "require": WordEntry("require", [PartOfSpeech.VERB], ["To need"], WordFrequency.CORE_500,
                         synonyms=["need", "demand"]),
    "allow": WordEntry("allow", [PartOfSpeech.VERB], ["To permit"], WordFrequency.CORE_500,
                       synonyms=["permit", "let"], antonyms=["forbid"]),
    "include": WordEntry("include", [PartOfSpeech.VERB], ["To contain"], WordFrequency.CORE_500,
                         synonyms=["contain", "comprise"], antonyms=["exclude"]),
    "provide": WordEntry("provide", [PartOfSpeech.VERB], ["To supply"], WordFrequency.CORE_500,
                         synonyms=["supply", "give"]),
    "accept": WordEntry("accept", [PartOfSpeech.VERB], ["To receive willingly"], WordFrequency.CORE_500,
                        synonyms=["receive", "agree"], antonyms=["reject"]),
    "add": WordEntry("add", [PartOfSpeech.VERB], ["To combine, to include"], WordFrequency.CORE_500,
                     synonyms=["include", "combine"], antonyms=["remove", "subtract"]),
    "remove": WordEntry("remove", [PartOfSpeech.VERB], ["To take away"], WordFrequency.CORE_500,
                        synonyms=["eliminate", "delete"], antonyms=["add"]),
    "share": WordEntry("share", [PartOfSpeech.VERB], ["To divide, to give part"], WordFrequency.CORE_500,
                       synonyms=["divide", "distribute"]),
    "connect": WordEntry("connect", [PartOfSpeech.VERB], ["To join together"], WordFrequency.CORE_1000,
                         synonyms=["join", "link"], antonyms=["disconnect"]),
    "choose": WordEntry("choose", [PartOfSpeech.VERB], ["To select"], WordFrequency.CORE_500,
                        synonyms=["select", "pick"]),
    "need": WordEntry("need", [PartOfSpeech.VERB, PartOfSpeech.NOUN], ["To require"], WordFrequency.CORE_500,
                      synonyms=["require", "want"]),
    "offer": WordEntry("offer", [PartOfSpeech.VERB], ["To present, to propose"], WordFrequency.CORE_500,
                       synonyms=["present", "propose"]),
    "order": WordEntry("order", [PartOfSpeech.VERB, PartOfSpeech.NOUN], ["To command, to arrange"], WordFrequency.CORE_500,
                       synonyms=["command", "arrange"]),
}


# =============================================================================
# EXTENDED NOUNS (1000+ common nouns)
# =============================================================================

EXTENDED_NOUNS = {
    # People & Relationships
    "person": WordEntry("person", [PartOfSpeech.NOUN], ["An individual human"], WordFrequency.CORE_500, category="people"),
    "family": WordEntry("family", [PartOfSpeech.NOUN], ["Group of relatives"], WordFrequency.CORE_500, category="people"),
    "friend": WordEntry("friend", [PartOfSpeech.NOUN], ["A person one likes"], WordFrequency.CORE_500, 
                        antonyms=["enemy"], category="people"),
    "parent": WordEntry("parent", [PartOfSpeech.NOUN], ["Mother or father"], WordFrequency.CORE_500, category="people"),
    "mother": WordEntry("mother", [PartOfSpeech.NOUN], ["Female parent"], WordFrequency.CORE_500, category="people"),
    "father": WordEntry("father", [PartOfSpeech.NOUN], ["Male parent"], WordFrequency.CORE_500, category="people"),
    "brother": WordEntry("brother", [PartOfSpeech.NOUN], ["Male sibling"], WordFrequency.CORE_500, category="people"),
    "sister": WordEntry("sister", [PartOfSpeech.NOUN], ["Female sibling"], WordFrequency.CORE_500, category="people"),
    "son": WordEntry("son", [PartOfSpeech.NOUN], ["Male child"], WordFrequency.CORE_500, category="people"),
    "daughter": WordEntry("daughter", [PartOfSpeech.NOUN], ["Female child"], WordFrequency.CORE_500, category="people"),
    "husband": WordEntry("husband", [PartOfSpeech.NOUN], ["Married man"], WordFrequency.CORE_1000, category="people"),
    "wife": WordEntry("wife", [PartOfSpeech.NOUN], ["Married woman"], WordFrequency.CORE_1000, category="people"),
    "student": WordEntry("student", [PartOfSpeech.NOUN], ["One who studies"], WordFrequency.CORE_500, category="people"),
    "teacher": WordEntry("teacher", [PartOfSpeech.NOUN], ["One who teaches"], WordFrequency.CORE_500, category="people"),
    "doctor": WordEntry("doctor", [PartOfSpeech.NOUN], ["Medical professional"], WordFrequency.CORE_1000, category="people"),
    "employee": WordEntry("employee", [PartOfSpeech.NOUN], ["Worker"], WordFrequency.CORE_1000, 
                          synonyms=["worker"], category="people"),
    "manager": WordEntry("manager", [PartOfSpeech.NOUN], ["One who manages"], WordFrequency.CORE_1000, category="people"),
    "leader": WordEntry("leader", [PartOfSpeech.NOUN], ["One who leads"], WordFrequency.CORE_1000, 
                        antonyms=["follower"], category="people"),
    "customer": WordEntry("customer", [PartOfSpeech.NOUN], ["Buyer of goods/services"], WordFrequency.CORE_1000, 
                          synonyms=["client"], category="people"),
    "member": WordEntry("member", [PartOfSpeech.NOUN], ["Part of a group"], WordFrequency.CORE_500, category="people"),
    "group": WordEntry("group", [PartOfSpeech.NOUN], ["Collection of people/things"], WordFrequency.CORE_500),
    "team": WordEntry("team", [PartOfSpeech.NOUN], ["Group working together"], WordFrequency.CORE_500),
    "community": WordEntry("community", [PartOfSpeech.NOUN], ["Group with shared interests"], WordFrequency.CORE_1000),
    
    # Places
    "home": WordEntry("home", [PartOfSpeech.NOUN], ["Place where one lives"], WordFrequency.CORE_500, category="place"),
    "house": WordEntry("house", [PartOfSpeech.NOUN], ["Building for living"], WordFrequency.CORE_500, category="place"),
    "room": WordEntry("room", [PartOfSpeech.NOUN], ["Space in building"], WordFrequency.CORE_500, category="place"),
    "school": WordEntry("school", [PartOfSpeech.NOUN], ["Educational institution"], WordFrequency.CORE_500, category="place"),
    "office": WordEntry("office", [PartOfSpeech.NOUN], ["Place of work"], WordFrequency.CORE_500, category="place"),
    "city": WordEntry("city", [PartOfSpeech.NOUN], ["Large urban area"], WordFrequency.CORE_500, category="place"),
    "country": WordEntry("country", [PartOfSpeech.NOUN], ["Nation, rural area"], WordFrequency.CORE_500, category="place"),
    "market": WordEntry("market", [PartOfSpeech.NOUN], ["Place for buying/selling"], WordFrequency.CORE_500, category="place"),
    "store": WordEntry("store", [PartOfSpeech.NOUN], ["Shop"], WordFrequency.CORE_500, synonyms=["shop"], category="place"),
    "hospital": WordEntry("hospital", [PartOfSpeech.NOUN], ["Medical facility"], WordFrequency.CORE_1000, category="place"),
    "bank": WordEntry("bank", [PartOfSpeech.NOUN], ["Financial institution"], WordFrequency.CORE_1000, category="place"),
    "restaurant": WordEntry("restaurant", [PartOfSpeech.NOUN], ["Place to eat"], WordFrequency.CORE_1000, category="place"),
    "hotel": WordEntry("hotel", [PartOfSpeech.NOUN], ["Lodging place"], WordFrequency.CORE_1000, category="place"),
    "area": WordEntry("area", [PartOfSpeech.NOUN], ["Region, zone"], WordFrequency.CORE_500, synonyms=["region", "zone"]),
    "center": WordEntry("center", [PartOfSpeech.NOUN], ["Middle point"], WordFrequency.CORE_500, synonyms=["middle"]),
    "street": WordEntry("street", [PartOfSpeech.NOUN], ["Road in city"], WordFrequency.CORE_500, category="place"),
    "road": WordEntry("road", [PartOfSpeech.NOUN], ["Path for travel"], WordFrequency.CORE_500, category="place"),
    
    # Objects & Things
    "book": WordEntry("book", [PartOfSpeech.NOUN], ["Written work"], WordFrequency.CORE_500),
    "computer": WordEntry("computer", [PartOfSpeech.NOUN], ["Electronic device"], WordFrequency.CORE_500, category="technology"),
    "phone": WordEntry("phone", [PartOfSpeech.NOUN], ["Communication device"], WordFrequency.CORE_500, category="technology"),
    "car": WordEntry("car", [PartOfSpeech.NOUN], ["Motor vehicle"], WordFrequency.CORE_500, synonyms=["automobile"]),
    "money": WordEntry("money", [PartOfSpeech.NOUN], ["Currency"], WordFrequency.CORE_500, synonyms=["cash", "currency"]),
    "food": WordEntry("food", [PartOfSpeech.NOUN], ["Nourishment"], WordFrequency.CORE_500),
    "water": WordEntry("water", [PartOfSpeech.NOUN], ["H2O, liquid"], WordFrequency.CORE_500),
    "door": WordEntry("door", [PartOfSpeech.NOUN], ["Entrance barrier"], WordFrequency.CORE_500),
    "window": WordEntry("window", [PartOfSpeech.NOUN], ["Opening for light"], WordFrequency.CORE_500),
    "table": WordEntry("table", [PartOfSpeech.NOUN], ["Furniture with flat top"], WordFrequency.CORE_500),
    "chair": WordEntry("chair", [PartOfSpeech.NOUN], ["Seat with back"], WordFrequency.CORE_500),
    "bed": WordEntry("bed", [PartOfSpeech.NOUN], ["Furniture for sleeping"], WordFrequency.CORE_500),
    "paper": WordEntry("paper", [PartOfSpeech.NOUN], ["Writing material"], WordFrequency.CORE_500),
    "picture": WordEntry("picture", [PartOfSpeech.NOUN], ["Visual image"], WordFrequency.CORE_500, synonyms=["image", "photo"]),
    "letter": WordEntry("letter", [PartOfSpeech.NOUN], ["Written message, alphabet character"], WordFrequency.CORE_500),
    "word": WordEntry("word", [PartOfSpeech.NOUN], ["Unit of language"], WordFrequency.CORE_500),
    "number": WordEntry("number", [PartOfSpeech.NOUN], ["Numerical value"], WordFrequency.CORE_500),
    "information": WordEntry("information", [PartOfSpeech.NOUN], ["Data, knowledge"], WordFrequency.CORE_500, 
                             synonyms=["data", "facts"]),
    "example": WordEntry("example", [PartOfSpeech.NOUN], ["Instance, sample"], WordFrequency.CORE_500, 
                         synonyms=["instance", "sample"]),
    "problem": WordEntry("problem", [PartOfSpeech.NOUN], ["Difficulty, issue"], WordFrequency.CORE_500, 
                         synonyms=["issue", "difficulty"], antonyms=["solution"]),
    "solution": WordEntry("solution", [PartOfSpeech.NOUN], ["Answer, resolution"], WordFrequency.CORE_500, 
                          synonyms=["answer", "resolution"], antonyms=["problem"]),
    "idea": WordEntry("idea", [PartOfSpeech.NOUN], ["Thought, concept"], WordFrequency.CORE_500, 
                      synonyms=["concept", "thought"]),
    "reason": WordEntry("reason", [PartOfSpeech.NOUN], ["Cause, rationale"], WordFrequency.CORE_500, 
                        synonyms=["cause", "rationale"]),
    "result": WordEntry("result", [PartOfSpeech.NOUN], ["Outcome, consequence"], WordFrequency.CORE_500, 
                        synonyms=["outcome", "consequence"]),
    "fact": WordEntry("fact", [PartOfSpeech.NOUN], ["True statement"], WordFrequency.CORE_500, 
                      synonyms=["truth"], antonyms=["fiction"]),
    "point": WordEntry("point", [PartOfSpeech.NOUN], ["Position, purpose"], WordFrequency.CORE_500),
    "story": WordEntry("story", [PartOfSpeech.NOUN], ["Narrative, tale"], WordFrequency.CORE_500, 
                       synonyms=["tale", "narrative"]),
    "name": WordEntry("name", [PartOfSpeech.NOUN], ["Identifier, title"], WordFrequency.CORE_500),
    "level": WordEntry("level", [PartOfSpeech.NOUN], ["Degree, position"], WordFrequency.CORE_500, 
                       synonyms=["degree", "stage"]),
    "type": WordEntry("type", [PartOfSpeech.NOUN], ["Kind, category"], WordFrequency.CORE_500, 
                      synonyms=["kind", "sort"]),
    "form": WordEntry("form", [PartOfSpeech.NOUN], ["Shape, document"], WordFrequency.CORE_500, 
                      synonyms=["shape", "structure"]),
    "value": WordEntry("value", [PartOfSpeech.NOUN], ["Worth, importance"], WordFrequency.CORE_500, 
                       synonyms=["worth"]),
    "process": WordEntry("process", [PartOfSpeech.NOUN], ["Procedure, method"], WordFrequency.CORE_500, 
                         synonyms=["procedure", "method"]),
    "step": WordEntry("step", [PartOfSpeech.NOUN], ["Stage, footstep"], WordFrequency.CORE_500, 
                      synonyms=["stage"]),
    "project": WordEntry("project", [PartOfSpeech.NOUN], ["Undertaking, plan"], WordFrequency.CORE_500),
    "goal": WordEntry("goal", [PartOfSpeech.NOUN], ["Objective, aim"], WordFrequency.CORE_500, 
                      synonyms=["objective", "aim", "target"]),
    "issue": WordEntry("issue", [PartOfSpeech.NOUN], ["Problem, topic"], WordFrequency.CORE_500, 
                       synonyms=["problem", "matter"]),
    "decision": WordEntry("decision", [PartOfSpeech.NOUN], ["Choice made"], WordFrequency.CORE_500, 
                          synonyms=["choice"]),
    "action": WordEntry("action", [PartOfSpeech.NOUN], ["Deed, activity"], WordFrequency.CORE_500, 
                        synonyms=["deed", "act"]),
    "experience": WordEntry("experience", [PartOfSpeech.NOUN], ["Knowledge from doing"], WordFrequency.CORE_500),
    "service": WordEntry("service", [PartOfSpeech.NOUN], ["Assistance, duty"], WordFrequency.CORE_500, 
                         synonyms=["assistance"]),
    "research": WordEntry("research", [PartOfSpeech.NOUN], ["Investigation, study"], WordFrequency.CORE_1000, 
                          synonyms=["study", "investigation"]),
    "technology": WordEntry("technology", [PartOfSpeech.NOUN], ["Applied science"], WordFrequency.CORE_1000),
    "data": WordEntry("data", [PartOfSpeech.NOUN], ["Information, facts"], WordFrequency.CORE_1000, 
                      synonyms=["information"]),
    
    # Time-related nouns
    "time": WordEntry("time", [PartOfSpeech.NOUN], ["Duration, moment"], WordFrequency.CORE_100, category="time"),
    "day": WordEntry("day", [PartOfSpeech.NOUN], ["24-hour period"], WordFrequency.CORE_100, category="time"),
    "night": WordEntry("night", [PartOfSpeech.NOUN], ["Dark period"], WordFrequency.CORE_500, 
                       antonyms=["day"], category="time"),
    "morning": WordEntry("morning", [PartOfSpeech.NOUN], ["Early part of day"], WordFrequency.CORE_500, category="time"),
    "evening": WordEntry("evening", [PartOfSpeech.NOUN], ["Late part of day"], WordFrequency.CORE_500, category="time"),
    "hour": WordEntry("hour", [PartOfSpeech.NOUN], ["60 minutes"], WordFrequency.CORE_500, category="time"),
    "minute": WordEntry("minute", [PartOfSpeech.NOUN], ["60 seconds"], WordFrequency.CORE_500, category="time"),
    "second": WordEntry("second", [PartOfSpeech.NOUN], ["1/60 of minute"], WordFrequency.CORE_500, category="time"),
    "month": WordEntry("month", [PartOfSpeech.NOUN], ["~30 days"], WordFrequency.CORE_500, category="time"),
    "week": WordEntry("week", [PartOfSpeech.NOUN], ["7 days"], WordFrequency.CORE_500, category="time"),
    "year": WordEntry("year", [PartOfSpeech.NOUN], ["365 days"], WordFrequency.CORE_100, category="time"),
    "today": WordEntry("today", [PartOfSpeech.NOUN, PartOfSpeech.ADVERB], ["This day"], WordFrequency.CORE_500, category="time"),
    "tomorrow": WordEntry("tomorrow", [PartOfSpeech.NOUN, PartOfSpeech.ADVERB], ["Next day"], WordFrequency.CORE_500, 
                          antonyms=["yesterday"], category="time"),
    "yesterday": WordEntry("yesterday", [PartOfSpeech.NOUN, PartOfSpeech.ADVERB], ["Previous day"], WordFrequency.CORE_500, 
                           antonyms=["tomorrow"], category="time"),
    "future": WordEntry("future", [PartOfSpeech.NOUN], ["Time to come"], WordFrequency.CORE_500, 
                        antonyms=["past"], category="time"),
    "past": WordEntry("past", [PartOfSpeech.NOUN], ["Time gone by"], WordFrequency.CORE_500, 
                      antonyms=["future"], category="time"),
    "present": WordEntry("present", [PartOfSpeech.NOUN], ["Current time, gift"], WordFrequency.CORE_500, category="time"),
    
    # Nature
    "sun": WordEntry("sun", [PartOfSpeech.NOUN], ["Star at center of solar system"], WordFrequency.CORE_500, category="nature"),
    "moon": WordEntry("moon", [PartOfSpeech.NOUN], ["Earth's satellite"], WordFrequency.CORE_1000, category="nature"),
    "star": WordEntry("star", [PartOfSpeech.NOUN], ["Luminous celestial body"], WordFrequency.CORE_500, category="nature"),
    "sky": WordEntry("sky", [PartOfSpeech.NOUN], ["Atmosphere above"], WordFrequency.CORE_500, category="nature"),
    "air": WordEntry("air", [PartOfSpeech.NOUN], ["Atmosphere, gas we breathe"], WordFrequency.CORE_500, category="nature"),
    "earth": WordEntry("earth", [PartOfSpeech.NOUN], ["Our planet, soil"], WordFrequency.CORE_500, category="nature"),
    "fire": WordEntry("fire", [PartOfSpeech.NOUN], ["Combustion, flames"], WordFrequency.CORE_500, category="nature"),
    "tree": WordEntry("tree", [PartOfSpeech.NOUN], ["Tall plant with trunk"], WordFrequency.CORE_500, category="nature"),
    "flower": WordEntry("flower", [PartOfSpeech.NOUN], ["Blossom of plant"], WordFrequency.CORE_1000, category="nature"),
    "animal": WordEntry("animal", [PartOfSpeech.NOUN], ["Living creature"], WordFrequency.CORE_500, category="nature"),
    "dog": WordEntry("dog", [PartOfSpeech.NOUN], ["Canine pet"], WordFrequency.CORE_500, category="animal"),
    "cat": WordEntry("cat", [PartOfSpeech.NOUN], ["Feline pet"], WordFrequency.CORE_500, category="animal"),
    "bird": WordEntry("bird", [PartOfSpeech.NOUN], ["Feathered flying animal"], WordFrequency.CORE_500, category="animal"),
    "fish": WordEntry("fish", [PartOfSpeech.NOUN], ["Aquatic animal"], WordFrequency.CORE_500, category="animal"),
    
    # Body parts
    "body": WordEntry("body", [PartOfSpeech.NOUN], ["Physical structure"], WordFrequency.CORE_500, category="body"),
    "head": WordEntry("head", [PartOfSpeech.NOUN], ["Top of body"], WordFrequency.CORE_500, category="body"),
    "face": WordEntry("face", [PartOfSpeech.NOUN], ["Front of head"], WordFrequency.CORE_500, category="body"),
    "eye": WordEntry("eye", [PartOfSpeech.NOUN], ["Organ of sight"], WordFrequency.CORE_500, category="body"),
    "ear": WordEntry("ear", [PartOfSpeech.NOUN], ["Organ of hearing"], WordFrequency.CORE_500, category="body"),
    "nose": WordEntry("nose", [PartOfSpeech.NOUN], ["Organ of smell"], WordFrequency.CORE_1000, category="body"),
    "mouth": WordEntry("mouth", [PartOfSpeech.NOUN], ["Oral cavity"], WordFrequency.CORE_500, category="body"),
    "hand": WordEntry("hand", [PartOfSpeech.NOUN], ["End of arm"], WordFrequency.CORE_100, category="body"),
    "foot": WordEntry("foot", [PartOfSpeech.NOUN], ["End of leg"], WordFrequency.CORE_500, category="body"),
    "heart": WordEntry("heart", [PartOfSpeech.NOUN], ["Organ that pumps blood, center of emotion"], WordFrequency.CORE_500, category="body"),
    "mind": WordEntry("mind", [PartOfSpeech.NOUN], ["Seat of consciousness"], WordFrequency.CORE_500, category="body"),
    "brain": WordEntry("brain", [PartOfSpeech.NOUN], ["Organ of thought"], WordFrequency.CORE_1000, category="body"),
}


# =============================================================================
# EXTENDED ADJECTIVES (500+)
# =============================================================================

EXTENDED_ADJECTIVES = {
    # Qualities
    "beautiful": WordEntry("beautiful", [PartOfSpeech.ADJECTIVE], ["Pleasing to senses"], WordFrequency.CORE_500,
                           synonyms=["pretty", "gorgeous"], antonyms=["ugly"]),
    "ugly": WordEntry("ugly", [PartOfSpeech.ADJECTIVE], ["Unpleasant to look at"], WordFrequency.CORE_1000,
                      antonyms=["beautiful"]),
    "strong": WordEntry("strong", [PartOfSpeech.ADJECTIVE], ["Powerful"], WordFrequency.CORE_500,
                        synonyms=["powerful"], antonyms=["weak"]),
    "weak": WordEntry("weak", [PartOfSpeech.ADJECTIVE], ["Lacking strength"], WordFrequency.CORE_500,
                      antonyms=["strong"]),
    "fast": WordEntry("fast", [PartOfSpeech.ADJECTIVE], ["Quick"], WordFrequency.CORE_500,
                      synonyms=["quick", "rapid"], antonyms=["slow"]),
    "slow": WordEntry("slow", [PartOfSpeech.ADJECTIVE], ["Not fast"], WordFrequency.CORE_500,
                      antonyms=["fast"]),
    "hard": WordEntry("hard", [PartOfSpeech.ADJECTIVE], ["Solid, difficult"], WordFrequency.CORE_500,
                      synonyms=["difficult"], antonyms=["soft", "easy"]),
    "soft": WordEntry("soft", [PartOfSpeech.ADJECTIVE], ["Not hard"], WordFrequency.CORE_500,
                      antonyms=["hard"]),
    "hot": WordEntry("hot", [PartOfSpeech.ADJECTIVE], ["High temperature"], WordFrequency.CORE_500,
                     antonyms=["cold"]),
    "cold": WordEntry("cold", [PartOfSpeech.ADJECTIVE], ["Low temperature"], WordFrequency.CORE_500,
                      antonyms=["hot"]),
    "warm": WordEntry("warm", [PartOfSpeech.ADJECTIVE], ["Moderately hot"], WordFrequency.CORE_500,
                      antonyms=["cool"]),
    "cool": WordEntry("cool", [PartOfSpeech.ADJECTIVE], ["Moderately cold"], WordFrequency.CORE_500,
                      antonyms=["warm"]),
    "clean": WordEntry("clean", [PartOfSpeech.ADJECTIVE], ["Free from dirt"], WordFrequency.CORE_500,
                       antonyms=["dirty"]),
    "dirty": WordEntry("dirty", [PartOfSpeech.ADJECTIVE], ["Not clean"], WordFrequency.CORE_1000,
                       antonyms=["clean"]),
    "wet": WordEntry("wet", [PartOfSpeech.ADJECTIVE], ["Covered with water"], WordFrequency.CORE_1000,
                     antonyms=["dry"]),
    "dry": WordEntry("dry", [PartOfSpeech.ADJECTIVE], ["Without moisture"], WordFrequency.CORE_500,
                     antonyms=["wet"]),
    "full": WordEntry("full", [PartOfSpeech.ADJECTIVE], ["Filled completely"], WordFrequency.CORE_500,
                      antonyms=["empty"]),
    "empty": WordEntry("empty", [PartOfSpeech.ADJECTIVE], ["Containing nothing"], WordFrequency.CORE_500,
                       antonyms=["full"]),
    "heavy": WordEntry("heavy", [PartOfSpeech.ADJECTIVE], ["Having great weight"], WordFrequency.CORE_500,
                       antonyms=["light"]),
    "light": WordEntry("light", [PartOfSpeech.ADJECTIVE], ["Not heavy, bright"], WordFrequency.CORE_500,
                       antonyms=["heavy", "dark"]),
    "dark": WordEntry("dark", [PartOfSpeech.ADJECTIVE], ["Without light"], WordFrequency.CORE_500,
                      antonyms=["light", "bright"]),
    "bright": WordEntry("bright", [PartOfSpeech.ADJECTIVE], ["Full of light"], WordFrequency.CORE_500,
                        synonyms=["brilliant"], antonyms=["dark", "dim"]),
    "rich": WordEntry("rich", [PartOfSpeech.ADJECTIVE], ["Having much money"], WordFrequency.CORE_500,
                      synonyms=["wealthy"], antonyms=["poor"]),
    "poor": WordEntry("poor", [PartOfSpeech.ADJECTIVE], ["Having little money"], WordFrequency.CORE_500,
                      antonyms=["rich"]),
    "young": WordEntry("young", [PartOfSpeech.ADJECTIVE], ["Not old"], WordFrequency.CORE_500,
                       antonyms=["old"]),
    "old": WordEntry("old", [PartOfSpeech.ADJECTIVE], ["Having lived long"], WordFrequency.CORE_100,
                     antonyms=["young", "new"]),
    "new": WordEntry("new", [PartOfSpeech.ADJECTIVE], ["Recently made"], WordFrequency.CORE_100,
                     synonyms=["fresh"], antonyms=["old"]),
    "fresh": WordEntry("fresh", [PartOfSpeech.ADJECTIVE], ["New, not stale"], WordFrequency.CORE_500,
                       synonyms=["new"], antonyms=["stale"]),
    "safe": WordEntry("safe", [PartOfSpeech.ADJECTIVE], ["Free from danger"], WordFrequency.CORE_500,
                      synonyms=["secure"], antonyms=["dangerous"]),
    "dangerous": WordEntry("dangerous", [PartOfSpeech.ADJECTIVE], ["Likely to cause harm"], WordFrequency.CORE_1000,
                           synonyms=["risky", "hazardous"], antonyms=["safe"]),
    "true": WordEntry("true", [PartOfSpeech.ADJECTIVE], ["Conforming to fact"], WordFrequency.CORE_500,
                      synonyms=["correct", "accurate"], antonyms=["false"]),
    "false": WordEntry("false", [PartOfSpeech.ADJECTIVE], ["Not true"], WordFrequency.CORE_500,
                       synonyms=["incorrect", "wrong"], antonyms=["true"]),
    "real": WordEntry("real", [PartOfSpeech.ADJECTIVE], ["Actually existing"], WordFrequency.CORE_500,
                      synonyms=["genuine", "authentic"], antonyms=["fake", "imaginary"]),
    "fake": WordEntry("fake", [PartOfSpeech.ADJECTIVE], ["Not genuine"], WordFrequency.COMMON,
                      synonyms=["false", "counterfeit"], antonyms=["real", "genuine"]),
    "possible": WordEntry("possible", [PartOfSpeech.ADJECTIVE], ["Able to happen"], WordFrequency.CORE_500,
                          antonyms=["impossible"]),
    "impossible": WordEntry("impossible", [PartOfSpeech.ADJECTIVE], ["Not able to happen"], WordFrequency.CORE_1000,
                            antonyms=["possible"]),
    "easy": WordEntry("easy", [PartOfSpeech.ADJECTIVE], ["Not difficult"], WordFrequency.CORE_500,
                      synonyms=["simple"], antonyms=["difficult", "hard"]),
    "difficult": WordEntry("difficult", [PartOfSpeech.ADJECTIVE], ["Hard to do"], WordFrequency.CORE_500,
                           synonyms=["hard", "challenging"], antonyms=["easy"]),
    "simple": WordEntry("simple", [PartOfSpeech.ADJECTIVE], ["Easy to understand"], WordFrequency.CORE_500,
                        synonyms=["easy"], antonyms=["complex", "complicated"]),
    "complex": WordEntry("complex", [PartOfSpeech.ADJECTIVE], ["Having many parts"], WordFrequency.CORE_1000,
                         synonyms=["complicated"], antonyms=["simple"]),
    "happy": WordEntry("happy", [PartOfSpeech.ADJECTIVE], ["Feeling joy"], WordFrequency.CORE_500,
                       synonyms=["glad", "joyful"], antonyms=["sad", "unhappy"]),
    "sad": WordEntry("sad", [PartOfSpeech.ADJECTIVE], ["Feeling sorrow"], WordFrequency.CORE_500,
                     synonyms=["unhappy", "sorrowful"], antonyms=["happy"]),
    "angry": WordEntry("angry", [PartOfSpeech.ADJECTIVE], ["Feeling anger"], WordFrequency.CORE_500,
                       synonyms=["mad", "furious"], antonyms=["calm"]),
    "calm": WordEntry("calm", [PartOfSpeech.ADJECTIVE], ["Peaceful, not agitated"], WordFrequency.CORE_1000,
                      synonyms=["peaceful", "tranquil"], antonyms=["angry", "agitated"]),
    "afraid": WordEntry("afraid", [PartOfSpeech.ADJECTIVE], ["Feeling fear"], WordFrequency.CORE_500,
                        synonyms=["scared", "frightened"]),
    "excited": WordEntry("excited", [PartOfSpeech.ADJECTIVE], ["Feeling enthusiasm"], WordFrequency.CORE_1000,
                         synonyms=["enthusiastic", "thrilled"]),
    "tired": WordEntry("tired", [PartOfSpeech.ADJECTIVE], ["Needing rest"], WordFrequency.CORE_500,
                       synonyms=["exhausted", "weary"], antonyms=["energetic"]),
    "busy": WordEntry("busy", [PartOfSpeech.ADJECTIVE], ["Actively engaged"], WordFrequency.CORE_500,
                      synonyms=["occupied"], antonyms=["free", "idle"]),
    "free": WordEntry("free", [PartOfSpeech.ADJECTIVE], ["Not restricted"], WordFrequency.CORE_500,
                      antonyms=["busy", "restricted"]),
    "ready": WordEntry("ready", [PartOfSpeech.ADJECTIVE], ["Prepared"], WordFrequency.CORE_500,
                       synonyms=["prepared"]),
    "sure": WordEntry("sure", [PartOfSpeech.ADJECTIVE], ["Certain"], WordFrequency.CORE_500,
                      synonyms=["certain", "confident"], antonyms=["unsure"]),
    "clear": WordEntry("clear", [PartOfSpeech.ADJECTIVE], ["Easy to perceive"], WordFrequency.CORE_500,
                       synonyms=["obvious"], antonyms=["unclear", "vague"]),
    "nice": WordEntry("nice", [PartOfSpeech.ADJECTIVE], ["Pleasant, kind"], WordFrequency.CORE_500,
                      synonyms=["pleasant", "kind"]),
    "kind": WordEntry("kind", [PartOfSpeech.ADJECTIVE], ["Friendly, generous"], WordFrequency.CORE_500,
                      synonyms=["nice", "friendly"], antonyms=["mean", "cruel"]),
    "mean": WordEntry("mean", [PartOfSpeech.ADJECTIVE], ["Unkind"], WordFrequency.CORE_1000,
                      synonyms=["unkind", "cruel"], antonyms=["kind", "nice"]),
    "funny": WordEntry("funny", [PartOfSpeech.ADJECTIVE], ["Causing laughter"], WordFrequency.CORE_500,
                       synonyms=["humorous", "amusing"]),
    "serious": WordEntry("serious", [PartOfSpeech.ADJECTIVE], ["Not joking"], WordFrequency.CORE_500,
                         antonyms=["funny", "playful"]),
    "smart": WordEntry("smart", [PartOfSpeech.ADJECTIVE], ["Intelligent"], WordFrequency.CORE_500,
                       synonyms=["intelligent", "clever"], antonyms=["stupid"]),
    "stupid": WordEntry("stupid", [PartOfSpeech.ADJECTIVE], ["Lacking intelligence"], WordFrequency.CORE_1000,
                        synonyms=["dumb", "foolish"], antonyms=["smart", "intelligent"]),
    "perfect": WordEntry("perfect", [PartOfSpeech.ADJECTIVE], ["Without flaw"], WordFrequency.CORE_500,
                         synonyms=["flawless", "ideal"], antonyms=["imperfect"]),
    "wrong": WordEntry("wrong", [PartOfSpeech.ADJECTIVE], ["Incorrect"], WordFrequency.CORE_500,
                       synonyms=["incorrect"], antonyms=["right", "correct"]),
    "correct": WordEntry("correct", [PartOfSpeech.ADJECTIVE], ["Right, accurate"], WordFrequency.CORE_500,
                         synonyms=["right", "accurate"], antonyms=["wrong", "incorrect"]),
    "common": WordEntry("common", [PartOfSpeech.ADJECTIVE], ["Occurring frequently"], WordFrequency.CORE_500,
                        synonyms=["frequent", "usual"], antonyms=["rare", "uncommon"]),
    "rare": WordEntry("rare", [PartOfSpeech.ADJECTIVE], ["Not common"], WordFrequency.CORE_1000,
                      synonyms=["uncommon"], antonyms=["common"]),
    "special": WordEntry("special", [PartOfSpeech.ADJECTIVE], ["Distinctive, important"], WordFrequency.CORE_500,
                         synonyms=["unique", "distinctive"], antonyms=["ordinary"]),
    "normal": WordEntry("normal", [PartOfSpeech.ADJECTIVE], ["Standard, typical"], WordFrequency.CORE_500,
                        synonyms=["usual", "typical"], antonyms=["abnormal"]),
    "strange": WordEntry("strange", [PartOfSpeech.ADJECTIVE], ["Unusual, unfamiliar"], WordFrequency.CORE_500,
                         synonyms=["odd", "weird"], antonyms=["normal", "familiar"]),
    "main": WordEntry("main", [PartOfSpeech.ADJECTIVE], ["Primary, chief"], WordFrequency.CORE_500,
                      synonyms=["primary", "chief"]),
    "available": WordEntry("available", [PartOfSpeech.ADJECTIVE], ["Able to be used"], WordFrequency.CORE_500,
                           antonyms=["unavailable"]),
    "popular": WordEntry("popular", [PartOfSpeech.ADJECTIVE], ["Liked by many"], WordFrequency.CORE_1000,
                         antonyms=["unpopular"]),
    "successful": WordEntry("successful", [PartOfSpeech.ADJECTIVE], ["Achieving goals"], WordFrequency.CORE_1000,
                            antonyms=["unsuccessful"]),
    "necessary": WordEntry("necessary", [PartOfSpeech.ADJECTIVE], ["Required"], WordFrequency.CORE_500,
                           synonyms=["essential", "required"], antonyms=["unnecessary"]),
    "certain": WordEntry("certain", [PartOfSpeech.ADJECTIVE], ["Sure, specific"], WordFrequency.CORE_500,
                         synonyms=["sure"], antonyms=["uncertain"]),
    "similar": WordEntry("similar", [PartOfSpeech.ADJECTIVE], ["Nearly the same"], WordFrequency.CORE_500,
                         synonyms=["alike"], antonyms=["different"]),
}


# =============================================================================
# EXTENDED ADVERBS (200+)
# =============================================================================

EXTENDED_ADVERBS = {
    # Manner
    "quickly": WordEntry("quickly", [PartOfSpeech.ADVERB], ["In a fast manner"], WordFrequency.CORE_500,
                         synonyms=["rapidly", "swiftly"], antonyms=["slowly"]),
    "slowly": WordEntry("slowly", [PartOfSpeech.ADVERB], ["In a slow manner"], WordFrequency.CORE_500,
                        antonyms=["quickly"]),
    "carefully": WordEntry("carefully", [PartOfSpeech.ADVERB], ["With care"], WordFrequency.CORE_500,
                           antonyms=["carelessly"]),
    "easily": WordEntry("easily", [PartOfSpeech.ADVERB], ["Without difficulty"], WordFrequency.CORE_500,
                        antonyms=["difficultly"]),
    "clearly": WordEntry("clearly", [PartOfSpeech.ADVERB], ["In a clear manner"], WordFrequency.CORE_500),
    "probably": WordEntry("probably", [PartOfSpeech.ADVERB], ["Most likely"], WordFrequency.CORE_500,
                          synonyms=["likely"]),
    "certainly": WordEntry("certainly", [PartOfSpeech.ADVERB], ["Without doubt"], WordFrequency.CORE_500,
                           synonyms=["definitely", "surely"]),
    "actually": WordEntry("actually", [PartOfSpeech.ADVERB], ["In reality"], WordFrequency.CORE_500,
                          synonyms=["really"]),
    "really": WordEntry("really", [PartOfSpeech.ADVERB], ["In fact, very"], WordFrequency.CORE_500,
                        synonyms=["truly", "actually"]),
    "simply": WordEntry("simply", [PartOfSpeech.ADVERB], ["In a simple way"], WordFrequency.CORE_500),
    "exactly": WordEntry("exactly", [PartOfSpeech.ADVERB], ["Precisely"], WordFrequency.CORE_500,
                         synonyms=["precisely"]),
    "especially": WordEntry("especially", [PartOfSpeech.ADVERB], ["Particularly"], WordFrequency.CORE_500,
                            synonyms=["particularly"]),
    "completely": WordEntry("completely", [PartOfSpeech.ADVERB], ["Entirely"], WordFrequency.CORE_500,
                            synonyms=["totally", "entirely"]),
    "directly": WordEntry("directly", [PartOfSpeech.ADVERB], ["In a direct way"], WordFrequency.CORE_1000,
                          antonyms=["indirectly"]),
    "extremely": WordEntry("extremely", [PartOfSpeech.ADVERB], ["To a great degree"], WordFrequency.CORE_1000,
                           synonyms=["very"]),
    "highly": WordEntry("highly", [PartOfSpeech.ADVERB], ["To a great degree"], WordFrequency.CORE_1000),
    "generally": WordEntry("generally", [PartOfSpeech.ADVERB], ["Usually, broadly"], WordFrequency.CORE_1000,
                           synonyms=["usually"]),
    "usually": WordEntry("usually", [PartOfSpeech.ADVERB], ["Most often"], WordFrequency.CORE_500,
                         synonyms=["typically", "normally"]),
    "perhaps": WordEntry("perhaps", [PartOfSpeech.ADVERB], ["Maybe"], WordFrequency.CORE_500,
                         synonyms=["maybe", "possibly"]),
    "already": WordEntry("already", [PartOfSpeech.ADVERB], ["Before now"], WordFrequency.CORE_500),
    "finally": WordEntry("finally", [PartOfSpeech.ADVERB], ["At last"], WordFrequency.CORE_500,
                         synonyms=["eventually"]),
    "together": WordEntry("together", [PartOfSpeech.ADVERB], ["With each other"], WordFrequency.CORE_500,
                          antonyms=["apart", "separately"]),
    "almost": WordEntry("almost", [PartOfSpeech.ADVERB], ["Nearly"], WordFrequency.CORE_500,
                        synonyms=["nearly"]),
    "never": WordEntry("never", [PartOfSpeech.ADVERB], ["At no time"], WordFrequency.CORE_500,
                       antonyms=["always"]),
    "always": WordEntry("always", [PartOfSpeech.ADVERB], ["At all times"], WordFrequency.CORE_500,
                        antonyms=["never"]),
    "often": WordEntry("often", [PartOfSpeech.ADVERB], ["Frequently"], WordFrequency.CORE_500,
                       synonyms=["frequently"], antonyms=["rarely"]),
    "sometimes": WordEntry("sometimes", [PartOfSpeech.ADVERB], ["Occasionally"], WordFrequency.CORE_500,
                           synonyms=["occasionally"]),
    "soon": WordEntry("soon", [PartOfSpeech.ADVERB], ["In the near future"], WordFrequency.CORE_500,
                      synonyms=["shortly"]),
    "again": WordEntry("again", [PartOfSpeech.ADVERB], ["One more time"], WordFrequency.CORE_500),
    "still": WordEntry("still", [PartOfSpeech.ADVERB], ["Continuing"], WordFrequency.CORE_500),
    "yet": WordEntry("yet", [PartOfSpeech.ADVERB], ["Until now, nevertheless"], WordFrequency.CORE_500),
    "ever": WordEntry("ever", [PartOfSpeech.ADVERB], ["At any time"], WordFrequency.CORE_500),
    "quite": WordEntry("quite", [PartOfSpeech.ADVERB], ["Somewhat, completely"], WordFrequency.CORE_500),
    "rather": WordEntry("rather", [PartOfSpeech.ADVERB], ["Somewhat, preferably"], WordFrequency.CORE_500),
    "away": WordEntry("away", [PartOfSpeech.ADVERB], ["At a distance"], WordFrequency.CORE_500),
    "back": WordEntry("back", [PartOfSpeech.ADVERB], ["To the rear"], WordFrequency.CORE_500,
                      antonyms=["forward"]),
    "forward": WordEntry("forward", [PartOfSpeech.ADVERB], ["Toward the front"], WordFrequency.CORE_1000,
                         antonyms=["backward"]),
    "inside": WordEntry("inside", [PartOfSpeech.ADVERB], ["In the interior"], WordFrequency.CORE_500,
                        antonyms=["outside"]),
    "outside": WordEntry("outside", [PartOfSpeech.ADVERB], ["In the exterior"], WordFrequency.CORE_500,
                         antonyms=["inside"]),
    "however": WordEntry("however", [PartOfSpeech.ADVERB], ["Nevertheless"], WordFrequency.CORE_500,
                         synonyms=["nevertheless"]),
    "therefore": WordEntry("therefore", [PartOfSpeech.ADVERB], ["For that reason"], WordFrequency.CORE_1000,
                           synonyms=["thus", "hence"]),
    "instead": WordEntry("instead", [PartOfSpeech.ADVERB], ["As an alternative"], WordFrequency.CORE_1000),
}


def load_extended_vocabulary(vocab: EnglishVocabulary = None) -> EnglishVocabulary:
    """
    Load extended vocabulary into the vocabulary instance.
    
    Args:
        vocab: Optional existing vocabulary to extend
        
    Returns:
        Extended vocabulary instance
    """
    if vocab is None:
        vocab = get_vocabulary()
        
    # Add extended verbs
    for word, entry in EXTENDED_VERBS.items():
        vocab.add_word(entry)
        
    # Add extended nouns
    for word, entry in EXTENDED_NOUNS.items():
        vocab.add_word(entry)
        
    # Add extended adjectives
    for word, entry in EXTENDED_ADJECTIVES.items():
        vocab.add_word(entry)
        
    # Add extended adverbs
    for word, entry in EXTENDED_ADVERBS.items():
        vocab.add_word(entry)
        
    print(f"[ExtendedVocabulary] Loaded extended vocabulary. Total: {vocab.vocabulary_size()} words")
    
    return vocab


# =============================================================================
# VOCABULARY STATISTICS
# =============================================================================

def get_vocabulary_stats() -> Dict:
    """Get statistics about the vocabulary."""
    return {
        "core_100": len(EXTENDED_VERBS) + len(EXTENDED_NOUNS) + len(EXTENDED_ADJECTIVES) + len(EXTENDED_ADVERBS),
        "extended_verbs": len(EXTENDED_VERBS),
        "extended_nouns": len(EXTENDED_NOUNS),
        "extended_adjectives": len(EXTENDED_ADJECTIVES),
        "extended_adverbs": len(EXTENDED_ADVERBS),
        "total_extended": (
            len(EXTENDED_VERBS) + 
            len(EXTENDED_NOUNS) + 
            len(EXTENDED_ADJECTIVES) + 
            len(EXTENDED_ADVERBS)
        ),
        "fluency_estimate": {
            "A1_beginner": "~500-1,000 words",
            "A2_elementary": "~1,000-2,000 words",
            "B1_intermediate": "~2,000-4,000 words",
            "B2_upper_intermediate": "~4,000-8,000 words",
            "C1_advanced": "~8,000-16,000 words",
            "C2_mastery": "~16,000+ words",
            "native_adult": "~20,000-35,000 words"
        }
    }
