# unimind/models/native/vocabulary_massive.py
# Massive Vocabulary Expansion for C2 Level

"""
Massive Vocabulary Module

Contains thousands of additional words for C2 level fluency:
- Extensive verb forms
- Additional nouns
- Descriptive adjectives
- Manner adverbs
- Compound words
"""

from typing import Dict, List
from .vocabulary import WordEntry, PartOfSpeech, WordFrequency


# =============================================================================
# EXTENSIVE VERB COLLECTION (~500 additional verbs)
# =============================================================================

EXTENSIVE_VERBS = {
    # Perception verbs
    "perceive": WordEntry("perceive", [PartOfSpeech.VERB], ["Become aware of"], WordFrequency.COMMON),
    "glimpse": WordEntry("glimpse", [PartOfSpeech.VERB], ["See briefly"], WordFrequency.COMMON),
    "gaze": WordEntry("gaze", [PartOfSpeech.VERB], ["Look steadily"], WordFrequency.COMMON),
    "stare": WordEntry("stare", [PartOfSpeech.VERB], ["Look fixedly"], WordFrequency.COMMON),
    "glance": WordEntry("glance", [PartOfSpeech.VERB], ["Look quickly"], WordFrequency.COMMON),
    "peer": WordEntry("peer", [PartOfSpeech.VERB], ["Look closely"], WordFrequency.COMMON),
    "scan": WordEntry("scan", [PartOfSpeech.VERB], ["Examine quickly"], WordFrequency.COMMON),
    "scrutinize": WordEntry("scrutinize", [PartOfSpeech.VERB], ["Examine closely"], WordFrequency.COMMON),
    "inspect": WordEntry("inspect", [PartOfSpeech.VERB], ["Examine carefully"], WordFrequency.COMMON),
    "witness": WordEntry("witness", [PartOfSpeech.VERB], ["See happen"], WordFrequency.COMMON),
    "overhear": WordEntry("overhear", [PartOfSpeech.VERB], ["Hear accidentally"], WordFrequency.COMMON),
    "eavesdrop": WordEntry("eavesdrop", [PartOfSpeech.VERB], ["Listen secretly"], WordFrequency.COMMON),
    "detect": WordEntry("detect", [PartOfSpeech.VERB], ["Discover"], WordFrequency.COMMON),
    "discern": WordEntry("discern", [PartOfSpeech.VERB], ["Perceive"], WordFrequency.COMMON),
    "distinguish": WordEntry("distinguish", [PartOfSpeech.VERB], ["Tell apart"], WordFrequency.COMMON),
    
    # Motion verbs
    "dash": WordEntry("dash", [PartOfSpeech.VERB], ["Rush"], WordFrequency.COMMON),
    "rush": WordEntry("rush", [PartOfSpeech.VERB], ["Move quickly"], WordFrequency.COMMON),
    "hurry": WordEntry("hurry", [PartOfSpeech.VERB], ["Move fast"], WordFrequency.COMMON),
    "hasten": WordEntry("hasten", [PartOfSpeech.VERB], ["Speed up"], WordFrequency.COMMON),
    "accelerate": WordEntry("accelerate", [PartOfSpeech.VERB], ["Speed up"], WordFrequency.COMMON),
    "decelerate": WordEntry("decelerate", [PartOfSpeech.VERB], ["Slow down"], WordFrequency.COMMON),
    "crawl": WordEntry("crawl", [PartOfSpeech.VERB], ["Move slowly"], WordFrequency.COMMON),
    "creep": WordEntry("creep", [PartOfSpeech.VERB], ["Move quietly"], WordFrequency.COMMON),
    "sneak": WordEntry("sneak", [PartOfSpeech.VERB], ["Move stealthily"], WordFrequency.COMMON),
    "tiptoe": WordEntry("tiptoe", [PartOfSpeech.VERB], ["Walk quietly"], WordFrequency.COMMON),
    "stroll": WordEntry("stroll", [PartOfSpeech.VERB], ["Walk leisurely"], WordFrequency.COMMON),
    "wander": WordEntry("wander", [PartOfSpeech.VERB], ["Walk aimlessly"], WordFrequency.COMMON),
    "roam": WordEntry("roam", [PartOfSpeech.VERB], ["Move freely"], WordFrequency.COMMON),
    "drift": WordEntry("drift", [PartOfSpeech.VERB], ["Float"], WordFrequency.COMMON),
    "glide": WordEntry("glide", [PartOfSpeech.VERB], ["Move smoothly"], WordFrequency.COMMON),
    "slide": WordEntry("slide", [PartOfSpeech.VERB], ["Move smoothly"], WordFrequency.COMMON),
    "slip": WordEntry("slip", [PartOfSpeech.VERB], ["Slide accidentally"], WordFrequency.COMMON),
    "skid": WordEntry("skid", [PartOfSpeech.VERB], ["Slide uncontrolled"], WordFrequency.COMMON),
    "stumble": WordEntry("stumble", [PartOfSpeech.VERB], ["Trip"], WordFrequency.COMMON),
    "tumble": WordEntry("tumble", [PartOfSpeech.VERB], ["Fall"], WordFrequency.COMMON),
    "plunge": WordEntry("plunge", [PartOfSpeech.VERB], ["Dive"], WordFrequency.COMMON),
    "dive": WordEntry("dive", [PartOfSpeech.VERB], ["Plunge"], WordFrequency.COMMON),
    "leap": WordEntry("leap", [PartOfSpeech.VERB], ["Jump"], WordFrequency.COMMON),
    "hop": WordEntry("hop", [PartOfSpeech.VERB], ["Small jump"], WordFrequency.COMMON),
    "skip": WordEntry("skip", [PartOfSpeech.VERB], ["Jump lightly"], WordFrequency.COMMON),
    "bounce": WordEntry("bounce", [PartOfSpeech.VERB], ["Spring back"], WordFrequency.COMMON),
    "spring": WordEntry("spring", [PartOfSpeech.VERB], ["Jump suddenly"], WordFrequency.COMMON),
    "soar": WordEntry("soar", [PartOfSpeech.VERB], ["Rise high"], WordFrequency.COMMON),
    "hover": WordEntry("hover", [PartOfSpeech.VERB], ["Float in place"], WordFrequency.COMMON),
    "float": WordEntry("float", [PartOfSpeech.VERB], ["Rest on surface"], WordFrequency.COMMON),
    "sink": WordEntry("sink", [PartOfSpeech.VERB], ["Go down"], WordFrequency.COMMON),
    "submerge": WordEntry("submerge", [PartOfSpeech.VERB], ["Go underwater"], WordFrequency.COMMON),
    "emerge": WordEntry("emerge", [PartOfSpeech.VERB], ["Come out"], WordFrequency.COMMON),
    "surface": WordEntry("surface", [PartOfSpeech.VERB], ["Come up"], WordFrequency.COMMON),
    "ascend": WordEntry("ascend", [PartOfSpeech.VERB], ["Go up"], WordFrequency.COMMON),
    "descend": WordEntry("descend", [PartOfSpeech.VERB], ["Go down"], WordFrequency.COMMON),
    "retreat": WordEntry("retreat", [PartOfSpeech.VERB], ["Go back"], WordFrequency.COMMON),
    "advance": WordEntry("advance", [PartOfSpeech.VERB], ["Move forward"], WordFrequency.COMMON),
    "proceed": WordEntry("proceed", [PartOfSpeech.VERB], ["Continue"], WordFrequency.COMMON),
    "progress": WordEntry("progress", [PartOfSpeech.VERB], ["Move forward"], WordFrequency.COMMON),
    "navigate": WordEntry("navigate", [PartOfSpeech.VERB], ["Find way"], WordFrequency.COMMON),
    "traverse": WordEntry("traverse", [PartOfSpeech.VERB], ["Cross"], WordFrequency.COMMON),
    "bypass": WordEntry("bypass", [PartOfSpeech.VERB], ["Go around"], WordFrequency.COMMON),
    "detour": WordEntry("detour", [PartOfSpeech.VERB], ["Take alternative route"], WordFrequency.COMMON),
    "commute": WordEntry("commute", [PartOfSpeech.VERB], ["Travel regularly"], WordFrequency.COMMON),
    "migrate": WordEntry("migrate", [PartOfSpeech.VERB], ["Move seasonally"], WordFrequency.COMMON),
    "relocate": WordEntry("relocate", [PartOfSpeech.VERB], ["Move location"], WordFrequency.COMMON),
    "evacuate": WordEntry("evacuate", [PartOfSpeech.VERB], ["Leave quickly"], WordFrequency.COMMON),
    
    # Communication verbs
    "articulate": WordEntry("articulate", [PartOfSpeech.VERB], ["Express clearly"], WordFrequency.COMMON),
    "convey": WordEntry("convey", [PartOfSpeech.VERB], ["Communicate"], WordFrequency.COMMON),
    "express": WordEntry("express", [PartOfSpeech.VERB], ["Show, say"], WordFrequency.COMMON),
    "utter": WordEntry("utter", [PartOfSpeech.VERB], ["Speak"], WordFrequency.COMMON),
    "murmur": WordEntry("murmur", [PartOfSpeech.VERB], ["Speak softly"], WordFrequency.COMMON),
    "mumble": WordEntry("mumble", [PartOfSpeech.VERB], ["Speak unclearly"], WordFrequency.COMMON),
    "mutter": WordEntry("mutter", [PartOfSpeech.VERB], ["Speak quietly"], WordFrequency.COMMON),
    "stammer": WordEntry("stammer", [PartOfSpeech.VERB], ["Speak with pauses"], WordFrequency.COMMON),
    "stutter": WordEntry("stutter", [PartOfSpeech.VERB], ["Repeat sounds"], WordFrequency.COMMON),
    "exclaim": WordEntry("exclaim", [PartOfSpeech.VERB], ["Cry out"], WordFrequency.COMMON),
    "proclaim": WordEntry("proclaim", [PartOfSpeech.VERB], ["Announce officially"], WordFrequency.COMMON),
    "declare": WordEntry("declare", [PartOfSpeech.VERB], ["State formally"], WordFrequency.COMMON),
    "assert": WordEntry("assert", [PartOfSpeech.VERB], ["State confidently"], WordFrequency.COMMON),
    "affirm": WordEntry("affirm", [PartOfSpeech.VERB], ["Confirm"], WordFrequency.COMMON),
    "acknowledge": WordEntry("acknowledge", [PartOfSpeech.VERB], ["Recognize"], WordFrequency.COMMON),
    "concede": WordEntry("concede", [PartOfSpeech.VERB], ["Admit"], WordFrequency.COMMON),
    "confess": WordEntry("confess", [PartOfSpeech.VERB], ["Admit"], WordFrequency.COMMON),
    "disclose": WordEntry("disclose", [PartOfSpeech.VERB], ["Reveal"], WordFrequency.COMMON),
    "reveal": WordEntry("reveal", [PartOfSpeech.VERB], ["Show"], WordFrequency.COMMON),
    "expose": WordEntry("expose", [PartOfSpeech.VERB], ["Uncover"], WordFrequency.COMMON),
    "divulge": WordEntry("divulge", [PartOfSpeech.VERB], ["Reveal secret"], WordFrequency.COMMON),
    "betray": WordEntry("betray", [PartOfSpeech.VERB], ["Be disloyal"], WordFrequency.COMMON),
    "deceive": WordEntry("deceive", [PartOfSpeech.VERB], ["Mislead"], WordFrequency.COMMON),
    "mislead": WordEntry("mislead", [PartOfSpeech.VERB], ["Give wrong impression"], WordFrequency.COMMON),
    "exaggerate": WordEntry("exaggerate", [PartOfSpeech.VERB], ["Overstate"], WordFrequency.COMMON),
    "understate": WordEntry("understate", [PartOfSpeech.VERB], ["Minimize"], WordFrequency.COMMON),
    "emphasize": WordEntry("emphasize", [PartOfSpeech.VERB], ["Stress"], WordFrequency.COMMON),
    "highlight": WordEntry("highlight", [PartOfSpeech.VERB], ["Draw attention to"], WordFrequency.COMMON),
    "stress": WordEntry("stress", [PartOfSpeech.VERB], ["Emphasize"], WordFrequency.COMMON),
    "elaborate": WordEntry("elaborate", [PartOfSpeech.VERB], ["Explain in detail"], WordFrequency.COMMON),
    "specify": WordEntry("specify", [PartOfSpeech.VERB], ["State precisely"], WordFrequency.COMMON),
    "generalize": WordEntry("generalize", [PartOfSpeech.VERB], ["Make general"], WordFrequency.COMMON),
    "simplify": WordEntry("simplify", [PartOfSpeech.VERB], ["Make simple"], WordFrequency.COMMON),
    "complicate": WordEntry("complicate", [PartOfSpeech.VERB], ["Make complex"], WordFrequency.COMMON),
    "clarify": WordEntry("clarify", [PartOfSpeech.VERB], ["Make clear"], WordFrequency.COMMON),
    "confuse": WordEntry("confuse", [PartOfSpeech.VERB], ["Puzzle"], WordFrequency.COMMON),
    "perplex": WordEntry("perplex", [PartOfSpeech.VERB], ["Bewilder"], WordFrequency.COMMON),
    "baffle": WordEntry("baffle", [PartOfSpeech.VERB], ["Confuse"], WordFrequency.COMMON),
    "mystify": WordEntry("mystify", [PartOfSpeech.VERB], ["Puzzle"], WordFrequency.COMMON),
    
    # Cognitive verbs
    "contemplate": WordEntry("contemplate", [PartOfSpeech.VERB], ["Think deeply"], WordFrequency.COMMON),
    "deliberate": WordEntry("deliberate", [PartOfSpeech.VERB], ["Consider carefully"], WordFrequency.COMMON),
    "ponder": WordEntry("ponder", [PartOfSpeech.VERB], ["Think about"], WordFrequency.COMMON),
    "reflect": WordEntry("reflect", [PartOfSpeech.VERB], ["Think back"], WordFrequency.COMMON),
    "meditate": WordEntry("meditate", [PartOfSpeech.VERB], ["Think deeply"], WordFrequency.COMMON),
    "speculate": WordEntry("speculate", [PartOfSpeech.VERB], ["Guess"], WordFrequency.COMMON),
    "hypothesize": WordEntry("hypothesize", [PartOfSpeech.VERB], ["Form hypothesis"], WordFrequency.COMMON),
    "theorize": WordEntry("theorize", [PartOfSpeech.VERB], ["Form theory"], WordFrequency.COMMON),
    "conceive": WordEntry("conceive", [PartOfSpeech.VERB], ["Form idea"], WordFrequency.COMMON),
    "envision": WordEntry("envision", [PartOfSpeech.VERB], ["Imagine"], WordFrequency.COMMON),
    "visualize": WordEntry("visualize", [PartOfSpeech.VERB], ["Form mental image"], WordFrequency.COMMON),
    "foresee": WordEntry("foresee", [PartOfSpeech.VERB], ["See beforehand"], WordFrequency.COMMON),
    "anticipate": WordEntry("anticipate", [PartOfSpeech.VERB], ["Expect"], WordFrequency.COMMON),
    "predict": WordEntry("predict", [PartOfSpeech.VERB], ["Forecast"], WordFrequency.COMMON),
    "forecast": WordEntry("forecast", [PartOfSpeech.VERB], ["Predict"], WordFrequency.COMMON),
    "project": WordEntry("project", [PartOfSpeech.VERB], ["Estimate future"], WordFrequency.COMMON),
    "infer": WordEntry("infer", [PartOfSpeech.VERB], ["Deduce"], WordFrequency.COMMON),
    "imply": WordEntry("imply", [PartOfSpeech.VERB], ["Suggest"], WordFrequency.COMMON),
    "presume": WordEntry("presume", [PartOfSpeech.VERB], ["Assume"], WordFrequency.COMMON),
    "reckon": WordEntry("reckon", [PartOfSpeech.VERB], ["Think, calculate"], WordFrequency.COMMON),
    "surmise": WordEntry("surmise", [PartOfSpeech.VERB], ["Guess"], WordFrequency.COMMON),
    "suspect": WordEntry("suspect", [PartOfSpeech.VERB], ["Believe guilty"], WordFrequency.COMMON),
    "mistrust": WordEntry("mistrust", [PartOfSpeech.VERB], ["Not trust"], WordFrequency.COMMON),
    "distrust": WordEntry("distrust", [PartOfSpeech.VERB], ["Not trust"], WordFrequency.COMMON),
    "verify": WordEntry("verify", [PartOfSpeech.VERB], ["Confirm"], WordFrequency.COMMON),
    "validate": WordEntry("validate", [PartOfSpeech.VERB], ["Confirm valid"], WordFrequency.COMMON),
    "authenticate": WordEntry("authenticate", [PartOfSpeech.VERB], ["Verify genuine"], WordFrequency.COMMON),
    "corroborate": WordEntry("corroborate", [PartOfSpeech.VERB], ["Confirm"], WordFrequency.COMMON),
    "substantiate": WordEntry("substantiate", [PartOfSpeech.VERB], ["Prove"], WordFrequency.COMMON),
    "justify": WordEntry("justify", [PartOfSpeech.VERB], ["Show reason"], WordFrequency.COMMON),
    "rationalize": WordEntry("rationalize", [PartOfSpeech.VERB], ["Make rational"], WordFrequency.COMMON),
    
    # Manipulation verbs
    "manipulate": WordEntry("manipulate", [PartOfSpeech.VERB], ["Control skillfully"], WordFrequency.COMMON),
    "handle": WordEntry("handle", [PartOfSpeech.VERB], ["Manage"], WordFrequency.COMMON),
    "operate": WordEntry("operate", [PartOfSpeech.VERB], ["Control, work"], WordFrequency.COMMON),
    "maneuver": WordEntry("maneuver", [PartOfSpeech.VERB], ["Move skillfully"], WordFrequency.COMMON),
    "navigate": WordEntry("navigate", [PartOfSpeech.VERB], ["Guide through"], WordFrequency.COMMON),
    "steer": WordEntry("steer", [PartOfSpeech.VERB], ["Direct"], WordFrequency.COMMON),
    "guide": WordEntry("guide", [PartOfSpeech.VERB], ["Lead"], WordFrequency.COMMON),
    "direct": WordEntry("direct", [PartOfSpeech.VERB], ["Guide"], WordFrequency.COMMON),
    "conduct": WordEntry("conduct", [PartOfSpeech.VERB], ["Lead, carry out"], WordFrequency.COMMON),
    "orchestrate": WordEntry("orchestrate", [PartOfSpeech.VERB], ["Organize"], WordFrequency.COMMON),
    "coordinate": WordEntry("coordinate", [PartOfSpeech.VERB], ["Organize together"], WordFrequency.COMMON),
    "synchronize": WordEntry("synchronize", [PartOfSpeech.VERB], ["Make simultaneous"], WordFrequency.COMMON),
    "calibrate": WordEntry("calibrate", [PartOfSpeech.VERB], ["Adjust precisely"], WordFrequency.COMMON),
    "configure": WordEntry("configure", [PartOfSpeech.VERB], ["Set up"], WordFrequency.COMMON),
    "customize": WordEntry("customize", [PartOfSpeech.VERB], ["Modify to fit"], WordFrequency.COMMON),
    "personalize": WordEntry("personalize", [PartOfSpeech.VERB], ["Make personal"], WordFrequency.COMMON),
    "optimize": WordEntry("optimize", [PartOfSpeech.VERB], ["Make optimal"], WordFrequency.COMMON),
    "maximize": WordEntry("maximize", [PartOfSpeech.VERB], ["Make maximum"], WordFrequency.COMMON),
    "minimize": WordEntry("minimize", [PartOfSpeech.VERB], ["Make minimum"], WordFrequency.COMMON),
    "stabilize": WordEntry("stabilize", [PartOfSpeech.VERB], ["Make stable"], WordFrequency.COMMON),
    "neutralize": WordEntry("neutralize", [PartOfSpeech.VERB], ["Make neutral"], WordFrequency.COMMON),
    "normalize": WordEntry("normalize", [PartOfSpeech.VERB], ["Make normal"], WordFrequency.COMMON),
    "standardize": WordEntry("standardize", [PartOfSpeech.VERB], ["Make standard"], WordFrequency.COMMON),
    "regulate": WordEntry("regulate", [PartOfSpeech.VERB], ["Control"], WordFrequency.COMMON),
    "moderate": WordEntry("moderate", [PartOfSpeech.VERB], ["Keep within limits"], WordFrequency.COMMON),
    "monitor": WordEntry("monitor", [PartOfSpeech.VERB], ["Watch over"], WordFrequency.COMMON),
    "supervise": WordEntry("supervise", [PartOfSpeech.VERB], ["Oversee"], WordFrequency.COMMON),
    "oversee": WordEntry("oversee", [PartOfSpeech.VERB], ["Watch over"], WordFrequency.COMMON),
    "administer": WordEntry("administer", [PartOfSpeech.VERB], ["Manage"], WordFrequency.COMMON),
    "govern": WordEntry("govern", [PartOfSpeech.VERB], ["Rule"], WordFrequency.COMMON),
    "dominate": WordEntry("dominate", [PartOfSpeech.VERB], ["Control"], WordFrequency.COMMON),
    "command": WordEntry("command", [PartOfSpeech.VERB], ["Order"], WordFrequency.COMMON),
    "dictate": WordEntry("dictate", [PartOfSpeech.VERB], ["Order, speak for writing"], WordFrequency.COMMON),
    "enforce": WordEntry("enforce", [PartOfSpeech.VERB], ["Make obey"], WordFrequency.COMMON),
    "impose": WordEntry("impose", [PartOfSpeech.VERB], ["Force upon"], WordFrequency.COMMON),
    "mandate": WordEntry("mandate", [PartOfSpeech.VERB], ["Order officially"], WordFrequency.COMMON),
    "authorize": WordEntry("authorize", [PartOfSpeech.VERB], ["Give permission"], WordFrequency.COMMON),
    "sanction": WordEntry("sanction", [PartOfSpeech.VERB], ["Approve, penalize"], WordFrequency.COMMON),
    "endorse": WordEntry("endorse", [PartOfSpeech.VERB], ["Support"], WordFrequency.COMMON),
    "advocate": WordEntry("advocate", [PartOfSpeech.VERB], ["Support publicly"], WordFrequency.COMMON),
    "promote": WordEntry("promote", [PartOfSpeech.VERB], ["Advance, advertise"], WordFrequency.COMMON),
    "sponsor": WordEntry("sponsor", [PartOfSpeech.VERB], ["Support financially"], WordFrequency.COMMON),
    "subsidize": WordEntry("subsidize", [PartOfSpeech.VERB], ["Support with money"], WordFrequency.COMMON),
    "fund": WordEntry("fund", [PartOfSpeech.VERB], ["Provide money"], WordFrequency.COMMON),
    "finance": WordEntry("finance", [PartOfSpeech.VERB], ["Provide money"], WordFrequency.COMMON),
    "invest": WordEntry("invest", [PartOfSpeech.VERB], ["Put money in"], WordFrequency.COMMON),
    "allocate": WordEntry("allocate", [PartOfSpeech.VERB], ["Distribute"], WordFrequency.COMMON),
    "distribute": WordEntry("distribute", [PartOfSpeech.VERB], ["Give out"], WordFrequency.COMMON),
    "disperse": WordEntry("disperse", [PartOfSpeech.VERB], ["Scatter"], WordFrequency.COMMON),
    "disseminate": WordEntry("disseminate", [PartOfSpeech.VERB], ["Spread information"], WordFrequency.COMMON),
    "propagate": WordEntry("propagate", [PartOfSpeech.VERB], ["Spread"], WordFrequency.COMMON),
    "circulate": WordEntry("circulate", [PartOfSpeech.VERB], ["Move around"], WordFrequency.COMMON),
    "transmit": WordEntry("transmit", [PartOfSpeech.VERB], ["Send"], WordFrequency.COMMON),
    "broadcast": WordEntry("broadcast", [PartOfSpeech.VERB], ["Transmit widely"], WordFrequency.COMMON),
    "relay": WordEntry("relay", [PartOfSpeech.VERB], ["Pass on"], WordFrequency.COMMON),
    "forward": WordEntry("forward", [PartOfSpeech.VERB], ["Send on"], WordFrequency.COMMON),
    "route": WordEntry("route", [PartOfSpeech.VERB], ["Direct along path"], WordFrequency.COMMON),
    "channel": WordEntry("channel", [PartOfSpeech.VERB], ["Direct through"], WordFrequency.COMMON),
    "funnel": WordEntry("funnel", [PartOfSpeech.VERB], ["Direct into"], WordFrequency.COMMON),
    "divert": WordEntry("divert", [PartOfSpeech.VERB], ["Redirect"], WordFrequency.COMMON),
    "redirect": WordEntry("redirect", [PartOfSpeech.VERB], ["Send different way"], WordFrequency.COMMON),
    "reroute": WordEntry("reroute", [PartOfSpeech.VERB], ["Send different route"], WordFrequency.COMMON),
    "transfer": WordEntry("transfer", [PartOfSpeech.VERB], ["Move"], WordFrequency.COMMON),
    "transport": WordEntry("transport", [PartOfSpeech.VERB], ["Carry"], WordFrequency.COMMON),
    "convey": WordEntry("convey", [PartOfSpeech.VERB], ["Transport, communicate"], WordFrequency.COMMON),
    "deliver": WordEntry("deliver", [PartOfSpeech.VERB], ["Bring"], WordFrequency.COMMON),
    "dispatch": WordEntry("dispatch", [PartOfSpeech.VERB], ["Send off"], WordFrequency.COMMON),
    "ship": WordEntry("ship", [PartOfSpeech.VERB], ["Send by ship"], WordFrequency.COMMON),
    "export": WordEntry("export", [PartOfSpeech.VERB], ["Send abroad"], WordFrequency.COMMON),
    "import": WordEntry("import", [PartOfSpeech.VERB], ["Bring from abroad"], WordFrequency.COMMON),
    "smuggle": WordEntry("smuggle", [PartOfSpeech.VERB], ["Import illegally"], WordFrequency.COMMON),
    "traffic": WordEntry("traffic", [PartOfSpeech.VERB], ["Trade illegally"], WordFrequency.COMMON),
}


# =============================================================================
# EXTENSIVE NOUNS COLLECTION (~500 additional nouns)
# =============================================================================

EXTENSIVE_NOUNS = {
    # Abstract concepts
    "ambiguity": WordEntry("ambiguity", [PartOfSpeech.NOUN], ["Uncertainty"], WordFrequency.COMMON),
    "anomaly": WordEntry("anomaly", [PartOfSpeech.NOUN], ["Irregularity"], WordFrequency.COMMON),
    "authenticity": WordEntry("authenticity", [PartOfSpeech.NOUN], ["Genuineness"], WordFrequency.COMMON),
    "autonomy": WordEntry("autonomy", [PartOfSpeech.NOUN], ["Independence"], WordFrequency.COMMON),
    "bias": WordEntry("bias", [PartOfSpeech.NOUN], ["Prejudice"], WordFrequency.COMMON),
    "breakthrough": WordEntry("breakthrough", [PartOfSpeech.NOUN], ["Major discovery"], WordFrequency.COMMON),
    "catalyst": WordEntry("catalyst", [PartOfSpeech.NOUN], ["Trigger"], WordFrequency.COMMON),
    "clarity": WordEntry("clarity", [PartOfSpeech.NOUN], ["Clearness"], WordFrequency.COMMON),
    "cohesion": WordEntry("cohesion", [PartOfSpeech.NOUN], ["Unity"], WordFrequency.COMMON),
    "consensus": WordEntry("consensus", [PartOfSpeech.NOUN], ["General agreement"], WordFrequency.COMMON),
    "constraint": WordEntry("constraint", [PartOfSpeech.NOUN], ["Limitation"], WordFrequency.COMMON),
    "controversy": WordEntry("controversy", [PartOfSpeech.NOUN], ["Dispute"], WordFrequency.COMMON),
    "correlation": WordEntry("correlation", [PartOfSpeech.NOUN], ["Relationship"], WordFrequency.COMMON),
    "criterion": WordEntry("criterion", [PartOfSpeech.NOUN], ["Standard"], WordFrequency.COMMON),
    "deficiency": WordEntry("deficiency", [PartOfSpeech.NOUN], ["Lack"], WordFrequency.COMMON),
    "dilemma": WordEntry("dilemma", [PartOfSpeech.NOUN], ["Difficult choice"], WordFrequency.COMMON),
    "dimension": WordEntry("dimension", [PartOfSpeech.NOUN], ["Aspect"], WordFrequency.COMMON),
    "discrepancy": WordEntry("discrepancy", [PartOfSpeech.NOUN], ["Difference"], WordFrequency.COMMON),
    "disparity": WordEntry("disparity", [PartOfSpeech.NOUN], ["Inequality"], WordFrequency.COMMON),
    "distortion": WordEntry("distortion", [PartOfSpeech.NOUN], ["Misrepresentation"], WordFrequency.COMMON),
    "dynamics": WordEntry("dynamics", [PartOfSpeech.NOUN], ["Forces"], WordFrequency.COMMON),
    "efficacy": WordEntry("efficacy", [PartOfSpeech.NOUN], ["Effectiveness"], WordFrequency.COMMON),
    "emergence": WordEntry("emergence", [PartOfSpeech.NOUN], ["Arising"], WordFrequency.COMMON),
    "endeavor": WordEntry("endeavor", [PartOfSpeech.NOUN], ["Effort"], WordFrequency.COMMON),
    "entity": WordEntry("entity", [PartOfSpeech.NOUN], ["Being"], WordFrequency.COMMON),
    "equilibrium": WordEntry("equilibrium", [PartOfSpeech.NOUN], ["Balance"], WordFrequency.COMMON),
    "essence": WordEntry("essence", [PartOfSpeech.NOUN], ["Core nature"], WordFrequency.COMMON),
    "evolution": WordEntry("evolution", [PartOfSpeech.NOUN], ["Development"], WordFrequency.COMMON),
    "excerpt": WordEntry("excerpt", [PartOfSpeech.NOUN], ["Extract"], WordFrequency.COMMON),
    "exclusion": WordEntry("exclusion", [PartOfSpeech.NOUN], ["Leaving out"], WordFrequency.COMMON),
    "expertise": WordEntry("expertise", [PartOfSpeech.NOUN], ["Expert skill"], WordFrequency.COMMON),
    "exploitation": WordEntry("exploitation", [PartOfSpeech.NOUN], ["Using unfairly"], WordFrequency.COMMON),
    "exposure": WordEntry("exposure", [PartOfSpeech.NOUN], ["Being exposed"], WordFrequency.COMMON),
    "extension": WordEntry("extension", [PartOfSpeech.NOUN], ["Expansion"], WordFrequency.COMMON),
    "extraction": WordEntry("extraction", [PartOfSpeech.NOUN], ["Removal"], WordFrequency.COMMON),
    "faction": WordEntry("faction", [PartOfSpeech.NOUN], ["Group within group"], WordFrequency.COMMON),
    "fluctuation": WordEntry("fluctuation", [PartOfSpeech.NOUN], ["Variation"], WordFrequency.COMMON),
    "framework": WordEntry("framework", [PartOfSpeech.NOUN], ["Structure"], WordFrequency.COMMON),
    "friction": WordEntry("friction", [PartOfSpeech.NOUN], ["Resistance"], WordFrequency.COMMON),
    "fusion": WordEntry("fusion", [PartOfSpeech.NOUN], ["Combination"], WordFrequency.COMMON),
    "gradient": WordEntry("gradient", [PartOfSpeech.NOUN], ["Slope"], WordFrequency.COMMON),
    "hierarchy": WordEntry("hierarchy", [PartOfSpeech.NOUN], ["Ranking system"], WordFrequency.COMMON),
    "hypothesis": WordEntry("hypothesis", [PartOfSpeech.NOUN], ["Theory"], WordFrequency.COMMON),
    "ideology": WordEntry("ideology", [PartOfSpeech.NOUN], ["Belief system"], WordFrequency.COMMON),
    "implication": WordEntry("implication", [PartOfSpeech.NOUN], ["Consequence"], WordFrequency.COMMON),
    "incentive": WordEntry("incentive", [PartOfSpeech.NOUN], ["Motivation"], WordFrequency.COMMON),
    "incidence": WordEntry("incidence", [PartOfSpeech.NOUN], ["Occurrence rate"], WordFrequency.COMMON),
    "inclination": WordEntry("inclination", [PartOfSpeech.NOUN], ["Tendency"], WordFrequency.COMMON),
    "index": WordEntry("index", [PartOfSpeech.NOUN], ["List, indicator"], WordFrequency.COMMON),
    "infrastructure": WordEntry("infrastructure", [PartOfSpeech.NOUN], ["Basic systems"], WordFrequency.COMMON),
    "innovation": WordEntry("innovation", [PartOfSpeech.NOUN], ["New idea"], WordFrequency.COMMON),
    "insight": WordEntry("insight", [PartOfSpeech.NOUN], ["Understanding"], WordFrequency.COMMON),
    "instance": WordEntry("instance", [PartOfSpeech.NOUN], ["Example"], WordFrequency.COMMON),
    "integrity": WordEntry("integrity", [PartOfSpeech.NOUN], ["Honesty"], WordFrequency.COMMON),
    "intensity": WordEntry("intensity", [PartOfSpeech.NOUN], ["Strength"], WordFrequency.COMMON),
    "intervention": WordEntry("intervention", [PartOfSpeech.NOUN], ["Interference"], WordFrequency.COMMON),
    "intuition": WordEntry("intuition", [PartOfSpeech.NOUN], ["Instinct"], WordFrequency.COMMON),
    "inventory": WordEntry("inventory", [PartOfSpeech.NOUN], ["Stock list"], WordFrequency.COMMON),
    "justification": WordEntry("justification", [PartOfSpeech.NOUN], ["Reason"], WordFrequency.COMMON),
    "leverage": WordEntry("leverage", [PartOfSpeech.NOUN], ["Influence"], WordFrequency.COMMON),
    "liability": WordEntry("liability", [PartOfSpeech.NOUN], ["Responsibility"], WordFrequency.COMMON),
    "magnitude": WordEntry("magnitude", [PartOfSpeech.NOUN], ["Size"], WordFrequency.COMMON),
    "manipulation": WordEntry("manipulation", [PartOfSpeech.NOUN], ["Control"], WordFrequency.COMMON),
    "mechanism": WordEntry("mechanism", [PartOfSpeech.NOUN], ["System"], WordFrequency.COMMON),
    "momentum": WordEntry("momentum", [PartOfSpeech.NOUN], ["Force"], WordFrequency.COMMON),
    "monopoly": WordEntry("monopoly", [PartOfSpeech.NOUN], ["Exclusive control"], WordFrequency.COMMON),
    "motive": WordEntry("motive", [PartOfSpeech.NOUN], ["Reason"], WordFrequency.COMMON),
    "notion": WordEntry("notion", [PartOfSpeech.NOUN], ["Idea"], WordFrequency.COMMON),
    "nuance": WordEntry("nuance", [PartOfSpeech.NOUN], ["Subtle difference"], WordFrequency.COMMON),
    "obligation": WordEntry("obligation", [PartOfSpeech.NOUN], ["Duty"], WordFrequency.COMMON),
    "obstacle": WordEntry("obstacle", [PartOfSpeech.NOUN], ["Barrier"], WordFrequency.COMMON),
    "offset": WordEntry("offset", [PartOfSpeech.NOUN], ["Counterbalance"], WordFrequency.COMMON),
    "option": WordEntry("option", [PartOfSpeech.NOUN], ["Choice"], WordFrequency.COMMON),
    "orientation": WordEntry("orientation", [PartOfSpeech.NOUN], ["Direction"], WordFrequency.COMMON),
    "outcome": WordEntry("outcome", [PartOfSpeech.NOUN], ["Result"], WordFrequency.COMMON),
    "output": WordEntry("output", [PartOfSpeech.NOUN], ["Production"], WordFrequency.COMMON),
    "paradigm": WordEntry("paradigm", [PartOfSpeech.NOUN], ["Model"], WordFrequency.COMMON),
    "paradox": WordEntry("paradox", [PartOfSpeech.NOUN], ["Contradiction"], WordFrequency.COMMON),
    "parameter": WordEntry("parameter", [PartOfSpeech.NOUN], ["Limit"], WordFrequency.COMMON),
    "participation": WordEntry("participation", [PartOfSpeech.NOUN], ["Taking part"], WordFrequency.COMMON),
    "perspective": WordEntry("perspective", [PartOfSpeech.NOUN], ["View"], WordFrequency.COMMON),
    "phenomenon": WordEntry("phenomenon", [PartOfSpeech.NOUN], ["Occurrence"], WordFrequency.COMMON),
    "philosophy": WordEntry("philosophy", [PartOfSpeech.NOUN], ["Belief system"], WordFrequency.COMMON),
    "pioneer": WordEntry("pioneer", [PartOfSpeech.NOUN], ["First developer"], WordFrequency.COMMON),
    "plateau": WordEntry("plateau", [PartOfSpeech.NOUN], ["Flat period"], WordFrequency.COMMON),
    "portfolio": WordEntry("portfolio", [PartOfSpeech.NOUN], ["Collection"], WordFrequency.COMMON),
    "precedent": WordEntry("precedent", [PartOfSpeech.NOUN], ["Previous example"], WordFrequency.COMMON),
    "precision": WordEntry("precision", [PartOfSpeech.NOUN], ["Accuracy"], WordFrequency.COMMON),
    "premise": WordEntry("premise", [PartOfSpeech.NOUN], ["Assumption"], WordFrequency.COMMON),
    "prerequisite": WordEntry("prerequisite", [PartOfSpeech.NOUN], ["Requirement"], WordFrequency.COMMON),
    "presumption": WordEntry("presumption", [PartOfSpeech.NOUN], ["Assumption"], WordFrequency.COMMON),
    "prevalence": WordEntry("prevalence", [PartOfSpeech.NOUN], ["Commonness"], WordFrequency.COMMON),
    "priority": WordEntry("priority", [PartOfSpeech.NOUN], ["Importance"], WordFrequency.COMMON),
    "probability": WordEntry("probability", [PartOfSpeech.NOUN], ["Likelihood"], WordFrequency.COMMON),
    "productivity": WordEntry("productivity", [PartOfSpeech.NOUN], ["Efficiency"], WordFrequency.COMMON),
    "progression": WordEntry("progression", [PartOfSpeech.NOUN], ["Advancement"], WordFrequency.COMMON),
    "projection": WordEntry("projection", [PartOfSpeech.NOUN], ["Forecast"], WordFrequency.COMMON),
    "proliferation": WordEntry("proliferation", [PartOfSpeech.NOUN], ["Rapid increase"], WordFrequency.COMMON),
    "proportion": WordEntry("proportion", [PartOfSpeech.NOUN], ["Ratio"], WordFrequency.COMMON),
    "proposition": WordEntry("proposition", [PartOfSpeech.NOUN], ["Proposal"], WordFrequency.COMMON),
    "prospect": WordEntry("prospect", [PartOfSpeech.NOUN], ["Possibility"], WordFrequency.COMMON),
    "protocol": WordEntry("protocol", [PartOfSpeech.NOUN], ["Procedure"], WordFrequency.COMMON),
    "proximity": WordEntry("proximity", [PartOfSpeech.NOUN], ["Nearness"], WordFrequency.COMMON),
    "quota": WordEntry("quota", [PartOfSpeech.NOUN], ["Limit"], WordFrequency.COMMON),
    "ratio": WordEntry("ratio", [PartOfSpeech.NOUN], ["Proportion"], WordFrequency.COMMON),
    "rationale": WordEntry("rationale", [PartOfSpeech.NOUN], ["Reasoning"], WordFrequency.COMMON),
    "realm": WordEntry("realm", [PartOfSpeech.NOUN], ["Domain"], WordFrequency.COMMON),
    "recession": WordEntry("recession", [PartOfSpeech.NOUN], ["Economic decline"], WordFrequency.COMMON),
    "recipient": WordEntry("recipient", [PartOfSpeech.NOUN], ["Receiver"], WordFrequency.COMMON),
    "recovery": WordEntry("recovery", [PartOfSpeech.NOUN], ["Return to normal"], WordFrequency.COMMON),
    "referendum": WordEntry("referendum", [PartOfSpeech.NOUN], ["Public vote"], WordFrequency.COMMON),
    "regime": WordEntry("regime", [PartOfSpeech.NOUN], ["Government system"], WordFrequency.COMMON),
    "regression": WordEntry("regression", [PartOfSpeech.NOUN], ["Going backward"], WordFrequency.COMMON),
    "reinforcement": WordEntry("reinforcement", [PartOfSpeech.NOUN], ["Strengthening"], WordFrequency.COMMON),
    "relevance": WordEntry("relevance", [PartOfSpeech.NOUN], ["Pertinence"], WordFrequency.COMMON),
    "reliability": WordEntry("reliability", [PartOfSpeech.NOUN], ["Dependability"], WordFrequency.COMMON),
    "remainder": WordEntry("remainder", [PartOfSpeech.NOUN], ["Rest"], WordFrequency.COMMON),
    "remedy": WordEntry("remedy", [PartOfSpeech.NOUN], ["Solution"], WordFrequency.COMMON),
    "renaissance": WordEntry("renaissance", [PartOfSpeech.NOUN], ["Rebirth"], WordFrequency.COMMON),
    "replication": WordEntry("replication", [PartOfSpeech.NOUN], ["Copying"], WordFrequency.COMMON),
    "representation": WordEntry("representation", [PartOfSpeech.NOUN], ["Depiction"], WordFrequency.COMMON),
    "reputation": WordEntry("reputation", [PartOfSpeech.NOUN], ["Public image"], WordFrequency.COMMON),
    "reservation": WordEntry("reservation", [PartOfSpeech.NOUN], ["Doubt, booking"], WordFrequency.COMMON),
    "residue": WordEntry("residue", [PartOfSpeech.NOUN], ["Remainder"], WordFrequency.COMMON),
    "resolution": WordEntry("resolution", [PartOfSpeech.NOUN], ["Solution"], WordFrequency.COMMON),
    "resource": WordEntry("resource", [PartOfSpeech.NOUN], ["Supply"], WordFrequency.COMMON),
    "restoration": WordEntry("restoration", [PartOfSpeech.NOUN], ["Renewal"], WordFrequency.COMMON),
    "restraint": WordEntry("restraint", [PartOfSpeech.NOUN], ["Control"], WordFrequency.COMMON),
    "restriction": WordEntry("restriction", [PartOfSpeech.NOUN], ["Limitation"], WordFrequency.COMMON),
    "retention": WordEntry("retention", [PartOfSpeech.NOUN], ["Keeping"], WordFrequency.COMMON),
    "revelation": WordEntry("revelation", [PartOfSpeech.NOUN], ["Discovery"], WordFrequency.COMMON),
    "revenue": WordEntry("revenue", [PartOfSpeech.NOUN], ["Income"], WordFrequency.COMMON),
    "revision": WordEntry("revision", [PartOfSpeech.NOUN], ["Amendment"], WordFrequency.COMMON),
    "revolution": WordEntry("revolution", [PartOfSpeech.NOUN], ["Major change"], WordFrequency.COMMON),
    "rhetoric": WordEntry("rhetoric", [PartOfSpeech.NOUN], ["Persuasive language"], WordFrequency.COMMON),
    "rigor": WordEntry("rigor", [PartOfSpeech.NOUN], ["Strictness"], WordFrequency.COMMON),
    "sanction": WordEntry("sanction", [PartOfSpeech.NOUN], ["Permission, penalty"], WordFrequency.COMMON),
    "scenario": WordEntry("scenario", [PartOfSpeech.NOUN], ["Possible situation"], WordFrequency.COMMON),
    "scheme": WordEntry("scheme", [PartOfSpeech.NOUN], ["Plan"], WordFrequency.COMMON),
    "scope": WordEntry("scope", [PartOfSpeech.NOUN], ["Range"], WordFrequency.COMMON),
    "sequence": WordEntry("sequence", [PartOfSpeech.NOUN], ["Order"], WordFrequency.COMMON),
    "series": WordEntry("series", [PartOfSpeech.NOUN], ["Sequence"], WordFrequency.COMMON),
    "session": WordEntry("session", [PartOfSpeech.NOUN], ["Meeting"], WordFrequency.COMMON),
    "simulation": WordEntry("simulation", [PartOfSpeech.NOUN], ["Imitation"], WordFrequency.COMMON),
    "sophistication": WordEntry("sophistication", [PartOfSpeech.NOUN], ["Complexity"], WordFrequency.COMMON),
    "specification": WordEntry("specification", [PartOfSpeech.NOUN], ["Detail"], WordFrequency.COMMON),
    "spectrum": WordEntry("spectrum", [PartOfSpeech.NOUN], ["Range"], WordFrequency.COMMON),
    "sphere": WordEntry("sphere", [PartOfSpeech.NOUN], ["Area"], WordFrequency.COMMON),
    "stability": WordEntry("stability", [PartOfSpeech.NOUN], ["Steadiness"], WordFrequency.COMMON),
    "stance": WordEntry("stance", [PartOfSpeech.NOUN], ["Position"], WordFrequency.COMMON),
    "statistic": WordEntry("statistic", [PartOfSpeech.NOUN], ["Numerical data"], WordFrequency.COMMON),
    "stimulus": WordEntry("stimulus", [PartOfSpeech.NOUN], ["Trigger"], WordFrequency.COMMON),
    "strategy": WordEntry("strategy", [PartOfSpeech.NOUN], ["Plan"], WordFrequency.COMMON),
    "stratum": WordEntry("stratum", [PartOfSpeech.NOUN], ["Layer"], WordFrequency.COMMON),
    "subsidy": WordEntry("subsidy", [PartOfSpeech.NOUN], ["Financial aid"], WordFrequency.COMMON),
    "substance": WordEntry("substance", [PartOfSpeech.NOUN], ["Material"], WordFrequency.COMMON),
    "substitute": WordEntry("substitute", [PartOfSpeech.NOUN], ["Replacement"], WordFrequency.COMMON),
    "succession": WordEntry("succession", [PartOfSpeech.NOUN], ["Series"], WordFrequency.COMMON),
    "supplement": WordEntry("supplement", [PartOfSpeech.NOUN], ["Addition"], WordFrequency.COMMON),
    "surplus": WordEntry("surplus", [PartOfSpeech.NOUN], ["Excess"], WordFrequency.COMMON),
    "surveillance": WordEntry("surveillance", [PartOfSpeech.NOUN], ["Watching"], WordFrequency.COMMON),
    "sustainability": WordEntry("sustainability", [PartOfSpeech.NOUN], ["Maintainability"], WordFrequency.COMMON),
    "symbol": WordEntry("symbol", [PartOfSpeech.NOUN], ["Representation"], WordFrequency.COMMON),
    "symmetry": WordEntry("symmetry", [PartOfSpeech.NOUN], ["Balance"], WordFrequency.COMMON),
    "synthesis": WordEntry("synthesis", [PartOfSpeech.NOUN], ["Combination"], WordFrequency.COMMON),
    "tactic": WordEntry("tactic", [PartOfSpeech.NOUN], ["Method"], WordFrequency.COMMON),
    "target": WordEntry("target", [PartOfSpeech.NOUN], ["Goal"], WordFrequency.COMMON),
    "technique": WordEntry("technique", [PartOfSpeech.NOUN], ["Method"], WordFrequency.COMMON),
    "tendency": WordEntry("tendency", [PartOfSpeech.NOUN], ["Inclination"], WordFrequency.COMMON),
    "tension": WordEntry("tension", [PartOfSpeech.NOUN], ["Stress"], WordFrequency.COMMON),
    "terminology": WordEntry("terminology", [PartOfSpeech.NOUN], ["Terms"], WordFrequency.COMMON),
    "territory": WordEntry("territory", [PartOfSpeech.NOUN], ["Area"], WordFrequency.COMMON),
    "threshold": WordEntry("threshold", [PartOfSpeech.NOUN], ["Limit"], WordFrequency.COMMON),
    "tolerance": WordEntry("tolerance", [PartOfSpeech.NOUN], ["Acceptance"], WordFrequency.COMMON),
    "trajectory": WordEntry("trajectory", [PartOfSpeech.NOUN], ["Path"], WordFrequency.COMMON),
    "transaction": WordEntry("transaction", [PartOfSpeech.NOUN], ["Deal"], WordFrequency.COMMON),
    "transformation": WordEntry("transformation", [PartOfSpeech.NOUN], ["Change"], WordFrequency.COMMON),
    "transition": WordEntry("transition", [PartOfSpeech.NOUN], ["Change"], WordFrequency.COMMON),
    "transmission": WordEntry("transmission", [PartOfSpeech.NOUN], ["Sending"], WordFrequency.COMMON),
    "transparency": WordEntry("transparency", [PartOfSpeech.NOUN], ["Openness"], WordFrequency.COMMON),
    "trend": WordEntry("trend", [PartOfSpeech.NOUN], ["Direction"], WordFrequency.COMMON),
    "trigger": WordEntry("trigger", [PartOfSpeech.NOUN], ["Cause"], WordFrequency.COMMON),
    "turbulence": WordEntry("turbulence", [PartOfSpeech.NOUN], ["Instability"], WordFrequency.COMMON),
    "undertaking": WordEntry("undertaking", [PartOfSpeech.NOUN], ["Task"], WordFrequency.COMMON),
    "utility": WordEntry("utility", [PartOfSpeech.NOUN], ["Usefulness"], WordFrequency.COMMON),
    "validity": WordEntry("validity", [PartOfSpeech.NOUN], ["Correctness"], WordFrequency.COMMON),
    "variance": WordEntry("variance", [PartOfSpeech.NOUN], ["Difference"], WordFrequency.COMMON),
    "velocity": WordEntry("velocity", [PartOfSpeech.NOUN], ["Speed"], WordFrequency.COMMON),
    "venture": WordEntry("venture", [PartOfSpeech.NOUN], ["Undertaking"], WordFrequency.COMMON),
    "verification": WordEntry("verification", [PartOfSpeech.NOUN], ["Confirmation"], WordFrequency.COMMON),
    "versatility": WordEntry("versatility", [PartOfSpeech.NOUN], ["Adaptability"], WordFrequency.COMMON),
    "viability": WordEntry("viability", [PartOfSpeech.NOUN], ["Feasibility"], WordFrequency.COMMON),
    "vicinity": WordEntry("vicinity", [PartOfSpeech.NOUN], ["Area nearby"], WordFrequency.COMMON),
    "violation": WordEntry("violation", [PartOfSpeech.NOUN], ["Breach"], WordFrequency.COMMON),
    "visibility": WordEntry("visibility", [PartOfSpeech.NOUN], ["Being seen"], WordFrequency.COMMON),
    "vision": WordEntry("vision", [PartOfSpeech.NOUN], ["Sight, foresight"], WordFrequency.COMMON),
    "volatility": WordEntry("volatility", [PartOfSpeech.NOUN], ["Instability"], WordFrequency.COMMON),
    "volume": WordEntry("volume", [PartOfSpeech.NOUN], ["Amount"], WordFrequency.COMMON),
    "vulnerability": WordEntry("vulnerability", [PartOfSpeech.NOUN], ["Weakness"], WordFrequency.COMMON),
    "welfare": WordEntry("welfare", [PartOfSpeech.NOUN], ["Well-being"], WordFrequency.COMMON),
    "workforce": WordEntry("workforce", [PartOfSpeech.NOUN], ["Workers"], WordFrequency.COMMON),
    "yield": WordEntry("yield", [PartOfSpeech.NOUN], ["Return"], WordFrequency.COMMON),
    "zone": WordEntry("zone", [PartOfSpeech.NOUN], ["Area"], WordFrequency.COMMON),
}


def load_massive_vocabulary(vocab=None):
    """Load massive vocabulary for C2 level."""
    from .vocabulary import get_vocabulary
    
    if vocab is None:
        vocab = get_vocabulary()
        
    total_added = 0
    
    for word, entry in EXTENSIVE_VERBS.items():
        vocab.add_word(entry)
        total_added += 1
        
    for word, entry in EXTENSIVE_NOUNS.items():
        vocab.add_word(entry)
        total_added += 1
        
    print(f"[MassiveVocabulary] Loaded {total_added} advanced words")
    print(f"[MassiveVocabulary] Total vocabulary: {vocab.vocabulary_size()} words")
    
    return vocab


def get_massive_stats() -> dict:
    """Get massive vocabulary statistics."""
    return {
        "extensive_verbs": len(EXTENSIVE_VERBS),
        "extensive_nouns": len(EXTENSIVE_NOUNS),
        "total": len(EXTENSIVE_VERBS) + len(EXTENSIVE_NOUNS)
    }
