import os
import re

class CodeGenerator:
    def __init__(self):
        self.library_path = "scrolls/library"
        os.makedirs(self.library_path, exist_ok=True)

    def generate_scroll(self, scroll_name, implementation_code):
        """
        Generates a new Python scroll file in the library.
        
        Args:
            scroll_name (str): The name of the scroll (e.g., "scan_wifi").
            implementation_code (str): The Python code to execute inside the run() function.
        """
        # Sanitize filename
        filename = scroll_name.lower().replace(" ", "_") + ".py"
        file_path = os.path.join(self.library_path, filename)
        
        # Create the file content
        content = f'''# Dynamic Scroll: {scroll_name}
# Generated by Guardian CodeGenerator

def run(*args, **kwargs):
    """
    Executes the {scroll_name} scroll.
    """
    print(f"[Scroll: {scroll_name}] Executing...")
    try:
{self._indent(implementation_code, 8)}
        return "Success"
    except Exception as e:
        return f"Error in {scroll_name}: {{e}}"
'''
        
        with open(file_path, "w") as f:
            f.write(content)
            
        return file_path

    def _indent(self, text, spaces=4):
        indentation = " " * spaces
        return "\n".join([indentation + line if line.strip() else line for line in text.split("\n")])

    def propose_scroll_implementation(self, description):
        """
        Uses heuristics (or LLM stub) to generate code from a description.
        """
        # Simple heuristic for demonstration
        code = "pass"
        if "print" in description or "log" in description:
            match = re.search(r"print ['\"](.*)['\"]", description)
            msg = match.group(1) if match else "Log entry"
            code = f'print("{msg}")'
        elif "calculate" in description:
            code = "result = 42\nprint(f'Calculation result: {result}')"
        elif "device" in description:
            code = "print('Interacting with device subsystems...')"
        elif "scan" in description:
             code = '''from sensors.device_scanner import DeviceScanner
    scanner = DeviceScanner()
    # Note: This creates a new instance. ideally we access the global one.
    print(f"Scanning devices...")
    results = scanner.scan_all()
    print(f"Found: {results}")'''
            
        return code
